import {chromium} from 'playwright';import {spawn} from 'node:child_process';import net from 'node:net';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createNotebook,snapshot,response,parseBackup} from '../src/notebook.js';import {DEFAULT} from '../src/model.js';
const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
const origin=`http://127.0.0.1:${port}`,root='artifacts/correctness-review',server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'ignore',env:{...process.env,PORT:String(port)}});let browser,page;
const seed=(part,state)=>{const b=createNotebook('synthetic-edge-regression');b.mode='challenge';b.part=part;b.workbenches[part]=snapshot(state);return b;};
try{
 await mkdir(root,{recursive:true});for(let i=0;i<50;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const manifest=JSON.parse(await readFile('dist/build-manifest.json','utf8')),runs=[];
 for(const renderer of ['WebGL','Diagram']){
  const context=await browser.newContext({viewport:{width:1366,height:768},acceptDownloads:true}),errors=[];
  if(renderer==='Diagram')await context.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...args){return kind.startsWith('webgl')?null:get.call(this,kind,...args);};});
  const open=async book=>{const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(b=>{if(!sessionStorage.getItem('fixture-seeded')){localStorage.setItem('lever-lab-notebook-v1',JSON.stringify(b));sessionStorage.setItem('fixture-seeded','true');}},book);await p.goto(origin+(renderer==='Diagram'?'/?fallback=1':''));await p.waitForSelector('#lab-navigation');assert.equal(await p.locator('#app').getAttribute('data-ready'),renderer==='Diagram'?'fallback':'true');return p;};
  const book=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')));
  const click=a=>page.locator(`[data-lab="${a}"]`).click();
  const control=async(k,v)=>{await page.locator(`[data-control="${k}"]`).fill(String(v));await page.locator(`[data-control="${k}"]`).press('Tab');};
  // Global Reset during a release must retain an interrupted trial, never a default-state result.
  const unbalanced={...DEFAULT,loadMass:300},reset=seed('Q14d',unbalanced);reset.workbenches.Q14a=snapshot(unbalanced);response(reset,'Q14c','prediction','Synthetic prediction before Reset','A');page=await open(reset);
  await click('hold');await page.locator('#reset').click();await page.waitForTimeout(700);let b=await book();assert.equal(b.trials.at(-1).interrupted,true);assert.equal(b.trials.at(-1).result,null);assert.equal(b.trials.at(-1).settled,false);assert.doesNotThrow(()=>parseBackup(JSON.stringify(b)));await page.reload();await page.waitForSelector('#lab-navigation');assert.notEqual(await page.locator('#save-status').innerText(),'Unreadable Save Kept');await page.close();
  // Restore while the current apparatus is different; inspect the actual controls, saved state, and reload.
  const wanted={...DEFAULT,load:-75,effort:225,loadMass:300},imported=seed('Q14a',wanted);page=await open(createNotebook());await click('session');await page.locator('#restore-backup').setInputFiles({name:'synthetic-design.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>document.querySelector('#restore-preview').textContent.includes('Ready to restore'));await click('restore');assert.equal(await page.locator('#mass-load').inputValue(),'300');assert.equal(await page.locator('#distance-load').inputValue(),'75');assert.equal(await page.locator('#distance-effort').inputValue(),'225');assert.deepEqual((await book()).workbenches.Q14a.state,wanted);
  // Clear only this fixture's initialization hook by reloading in a fresh page of the same context.
  await page.close();page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+(renderer==='Diagram'?'/?fallback=1':''));await page.waitForSelector('#lab-navigation');assert.equal(await page.locator('#distance-load').inputValue(),'75');assert.equal(await page.locator('#distance-effort').inputValue(),'225');
  // Bad event payloads must be rejected atomically by the real restore UI.
  const bad=structuredClone(imported);bad.events.push({type:'part-checked',part:'Q1a',id:'Q1a',at:new Date().toISOString(),driver:'A'});await click('session');await page.locator('#restore-backup').setInputFiles({name:'bad-event.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>document.querySelector('#restore-preview').textContent.includes('not a supported'));assert.equal(await page.locator('[data-lab="restore"]').isDisabled(),true);assert.deepEqual((await book()).workbenches.Q14a.state,wanted);await page.close();
  // Q14's recorded balanced trial violates the mass constraint. Editing only the current load cannot fix it.
  const equal={...DEFAULT,effort:100,loadMass:100},design=seed('Q14d',equal);design.workbenches.Q14a=snapshot(equal);response(design,'Q14c','prediction','Synthetic balance prediction','A');response(design,'Q14d','observation','Level');response(design,'Q14d','notes','Synthetic retained observation','A');page=await open(design);await click('hold');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')).trials.at(-1).settled);await click('hold');await control('loadMass',200);await click('check');assert.match(await page.locator('#lab-feedback').innerText(),/recorded design/);assert.equal((await book()).checks.Q14d.complete,false);await control('effort',200);await click('hold');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')).trials.at(-1).settled);await click('check');assert.equal((await book()).checks.Q14d.complete,true);assert.equal((await book()).trials.length,2);await page.close();
  // Stale completion must disappear immediately, without erasing the historical successful check.
  page=await open(seed('Q3a',{...DEFAULT,effort:100,effortMass:200}));await click('check');assert.equal((await book()).checks.Q3a.complete,true);await control('effort',150);assert.match(await page.locator('#lab-feedback').innerText(),/Needs Recheck/);b=await book();assert.equal(b.checks.Q3a.complete,false);assert.ok(b.events.some(e=>e.type==='part-checked'&&e.check.complete));
  // Top-level Learn, nested reference, general Help, and real tooltip exposure remain attributable.
  await click('mode-learn');await page.locator('.vocabulary > summary').click();await page.locator('.vocabulary details').first().locator('summary').click();await page.locator('#help').click();await page.locator('#help-dialog .dialog-close').first().click();await page.locator('#model-help').focus();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')).events.some(e=>e.type==='support-viewed'&&e.source==='tooltip'));b=await book();for(const source of ['lesson','reference','help','tooltip'])assert.ok(b.events.some(e=>e.type==='support-viewed'&&e.source===source&&e.from==='Q3a'),source);assert.equal(b.returnTo,'Q3a');assert.doesNotThrow(()=>parseBackup(JSON.stringify(b)));await click('return');await click('session');const downloaded=page.waitForEvent('download');await click('report');await(await downloaded).saveAs(`${root}/${renderer}-support-report.html`);const html=await readFile(`${root}/${renderer}-support-report.html`,'utf8');assert.ok(html.includes('General Help'));assert.ok(html.includes('Missing logs do not establish independent performance'));
  assert.deepEqual(errors,[]);runs.push({renderer,passed:true,checks:['Reset interrupts pending trial','Interrupted autosave remains valid','Restore preserves non-default design in controls and reload','Malformed historical check rejected before replacement','Q14 validates recorded setup and requires retest after edits','Setup edit invalidates current status while preserving history','All support routes attributable and exported'],errors});await context.close();
 }
 await writeFile(`${root}/verification.json`,JSON.stringify({build:manifest.id,passed:true,runs},null,2));console.log('CORRECTNESS REGRESSIONS PASSED '+manifest.id);
}catch(e){if(page&&!page.isClosed())await page.screenshot({path:`${root}/failure.png`});throw e;}finally{await browser?.close();server.kill();}
