// Test instrumentation is served only to this browser suite, never packaged.
import {build} from 'esbuild';import {chromium} from 'playwright';import {spawn} from 'node:child_process';import net from 'node:net';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {selectQuestion,readBook} from './helpers/student-browser.mjs';import {parseBackup} from '../src/notebook.js';
const root='artifacts/responsive-layout';await mkdir(root,{recursive:true});
await build({stdin:{contents:`import {LeverScene} from './src/scene.js';const init=LeverScene.prototype.init;LeverScene.prototype.init=async function(){await init.call(this);window.layoutScene=this;};await import('./src/app.js');`,resolveDir:process.cwd()},bundle:true,format:'esm',outfile:root+'/test-only.js',loader:{'.jpg':'dataurl'}});
const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));const origin=`http://127.0.0.1:${port}`,server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'ignore',windowsHide:true,env:{...process.env,PORT:String(port)}});let browser,page;
try{
 for(let i=0;i<50;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const manifest=JSON.parse(await readFile('dist/build-manifest.json','utf8')),runs=[];
 for(const renderer of ['WebGL','Diagram']){
  const context=await browser.newContext({viewport:{width:1366,height:768}}),errors=[];page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('**/assets/app.js',r=>r.fulfill({path:root+'/test-only.js',contentType:'text/javascript'}));
  if(renderer==='Diagram')await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(k,...args){return k.startsWith('webgl')?null:get.call(this,k,...args);};});
  await page.goto(origin);await page.waitForSelector('[data-lab="begin"]');await page.locator('#controls-toggle').click();await page.waitForTimeout(250);await page.screenshot({path:`${root}/${renderer}-introduction.png`});await page.locator('[data-value="push"]').click();await page.locator('[data-lab="begin"]').click();
  const geometry=(configuration=null)=>page.evaluate(configuration=>{const s=window.layoutScene;if(configuration){s.state=configuration.state;s.apparatus.update(s.state,configuration.angle);s.scene.updateMatrixWorld(true);}const area=s.callbacks.viewBounds(),points=[];for(const root of [s.apparatus.moving,s.apparatus.base])root.traverse(o=>{if(!o.geometry||o.userData.attention)return;o.geometry.computeBoundingBox();const b=o.geometry.boundingBox;for(const x of [b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z])points.push(s.project(o.localToWorld(s.camera.position.clone().set(x,y,z))));});return {area,left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))};},configuration);
  const assertVisible=async configuration=>{let b;const fits=b=>b.left>=b.area.left-2&&b.right<=b.area.right+2&&b.top>=b.area.top-2&&b.bottom<=b.area.bottom+2;for(let attempt=0;attempt<30;attempt++){b=await geometry(configuration);if(fits(b))return b;await page.waitForTimeout(100);}assert.ok(fits(b),JSON.stringify(b));return b;};
  const sizes=[];
  for(const [width,height]of [[1920,1080],[1366,768],[1280,720],[1280,600],[1024,600]]){
   await page.setViewportSize({width,height});await page.waitForTimeout(250);if(renderer==='WebGL'){await assertVisible();await page.locator('#fit').click();}await page.waitForTimeout(180);
   const boxes=await page.evaluate(()=>{const rect=s=>{const b=document.querySelector(s).getBoundingClientRect();return {left:b.left,top:b.top,right:b.right,bottom:b.bottom,width:b.width,height:b.height};};return {header:rect('#top'),notebook:rect('#notebook'),controls:rect('#controls-panel'),scroll:rect('.notebook-content'),overflow:document.documentElement.scrollWidth>innerWidth+1,buttons:[...document.querySelectorAll('.header-controls button,.header-controls select')].filter(b=>!b.hidden).map(b=>{const r=b.getBoundingClientRect();return {id:b.id,left:r.left,right:r.right,top:r.top,bottom:r.bottom};})};});
   assert.equal(boxes.overflow,false);assert.ok(boxes.header.bottom<boxes.controls.top);assert.ok(boxes.controls.bottom<boxes.notebook.top);assert.ok(boxes.notebook.bottom<=height);assert.ok(boxes.scroll.height>=130);assert.ok(boxes.buttons.every(b=>b.left>=0&&b.right<=width&&b.top>=0&&b.bottom<=boxes.header.bottom));
   const lever=renderer==='WebGL'?await assertVisible():null;await page.screenshot({path:`${root}/${renderer}-${width}x${height}.png`});sizes.push({width,height,boxes,lever});if(height<=600){const scroller=page.locator('.notebook-content');await scroller.focus();await page.keyboard.press('PageDown');await page.waitForFunction(()=>document.querySelector('.notebook-content').scrollTop>0,null,{timeout:3000});assert.ok(await scroller.evaluate(e=>e.scrollTop>0),'short notebook must remain keyboard-scrollable');await page.locator('#fulcrum-position').focus();const input=await page.locator('#fulcrum-position').boundingBox(),rail=await page.locator('#controls-panel').boundingBox();assert.ok(input.y>=rail.y-1&&input.y+input.height<=rail.y+rail.height+1,'short controls must scroll focused input into view');await page.locator('#mass-load').focus();await scroller.evaluate(e=>e.scrollTop=0);}
  }
  await page.setViewportSize({width:1366,height:768});await page.waitForTimeout(250);
  for(const role of ['load','load','effort','load','fulcrum']){await page.locator(`[data-lab="identify"][data-pick="${role}"]`).focus();await page.keyboard.press('Enter');}assert.match(await page.locator('#identify-feedback').innerText(),/3 Of 3/);assert.equal(await page.evaluate(()=>document.activeElement.dataset.lab),'next');
  await selectQuestion(page,'Q14c');const text=page.locator('textarea[data-answer]').first();await text.fill('Synthetic layout continuity evidence.');await text.press('Tab');const before=await readBook(page);
  await page.locator('[data-lab="reference"]').click();await page.locator('[data-lab="back"]').click();assert.equal(await text.inputValue(),'Synthetic layout continuity evidence.');
  await page.locator('[data-lab="index"]').click();assert.equal(await page.locator('.question-tile').count(),64);await page.locator('[data-part="Q14b"]').click();await page.locator('[data-sketch-label]').fill('Synthetic Load');await page.locator('[data-lab="sketch-add"]').click();assert.ok((await readBook(page)).answers.Q14b);
  await page.locator('[data-lab="hide"]').click();await page.locator('#notebook-reopen').click();assert.equal(await page.locator('#notebook').isVisible(),true);
  await page.locator('#fulcrum-position').focus();await page.keyboard.press('Home');const pivotBox=await page.locator('#fulcrum-position').boundingBox();assert.ok(pivotBox.y+pivotBox.height<(await page.locator('#notebook').boundingBox()).y);await page.locator('#controls-toggle').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'controls-toggle');await page.locator('#controls-toggle').click();
  await page.locator('#help').click();await page.locator('#reduced').check();await page.locator('#help-dialog .dialog-close').first().click();assert.equal(await page.locator('#app').getAttribute('data-reduced-motion'),'true');
  await page.locator('#math-toggle').click();assert.equal(await page.locator('#math-panel').isVisible(),true);const a=await page.locator('#notebook').boundingBox(),b=await page.locator('footer').boundingBox();assert.ok(a.x+a.width<=b.x);await page.locator('#math-toggle').click();await page.waitForTimeout(250);
  if(renderer==='WebGL'){
   for(const fulcrum of [-175,0,175])for(const swap of [false,true])for(const angle of [-Math.PI/15,0,Math.PI/15]){await assertVisible({state:{loadMass:1000,effortMass:1000,load:swap?250:-250,effort:swap?-250:250,fulcrum},angle});}
   await page.locator('#side').click();await assertVisible();await page.locator('#orbit').click();await page.locator('#fit').click();await assertVisible();
  }
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.locator('[data-lab="hide"]').click();assert.equal(await page.locator('#notebook-reopen').isVisible(),true);await page.locator('#notebook-reopen').click();
  await page.setViewportSize({width:1366,height:768});await page.reload();await page.waitForSelector('#notebook');const resumed=await readBook(page);assert.deepEqual(resumed.answers.Q14c,before.answers.Q14c);assert.doesNotThrow(()=>parseBackup(JSON.stringify(resumed)));
  const oldId='0.1.0_Partners-In-Balance_local-1e3bd62e_build-020_20261001T121138Z_g181718cb56cb_web',old=JSON.parse(await readFile(`artifacts/review-packages/${oldId}/review/guided-full/${renderer}-complete-backup.json`,'utf8'));await page.addInitScript(old=>localStorage.setItem('lever-lab-notebook-v1',JSON.stringify(old)),old);await page.reload();await page.waitForSelector('#notebook');const restored=await readBook(page);assert.deepEqual(restored.answers,old.answers);assert.deepEqual(restored.trials,old.trials);assert.deepEqual(restored.history,old.history);assert.equal(Object.values(restored.checks).filter(c=>c.complete).length,66);
  assert.deepEqual(errors,[]);runs.push({renderer,passed:true,sizes,errors,checks:['all existing header controls retained','bottom notebook and left controls do not overlap','full apparatus including extreme positions','question index and reference return','long reasoning and keyboard sketch','hide/reopen and keyboard focus','reduced motion','math beside notebook','resize and reload continuity','complete build-020 work preserved']});await context.close();
 }
 await writeFile(root+'/verification.json',JSON.stringify({build:manifest.id,passed:true,runs,limits:['Software-rendered Chrome, not a physical Chromebook measurement.','Temporary camera instrumentation is excluded from the playable artifact.']},null,2));console.log('RESPONSIVE LAYOUT PASS '+manifest.id);
}catch(e){if(page&&!page.isClosed())await page.screenshot({path:root+'/failure.png'});throw e;}finally{await browser?.close();server.kill();}
