import {chromium} from 'playwright';import {spawn} from 'node:child_process';import net from 'node:net';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));const origin=`http://127.0.0.1:${port}`,server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'ignore',env:{...process.env,PORT:String(port)}});let browser;
try{for(let i=0;i<50;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1366,height:768}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForSelector('#lab-navigation');
 await page.locator('[data-lab="mode-challenge"]').click();await page.locator('#question-select').selectOption('13');await page.locator('#part-select').selectOption('Q13b');await page.locator('[data-answer="prediction"]').fill('Synthetic original prediction: extend effort to raise load.');await page.locator('#part-select').selectOption('Q13c');await page.locator('[data-control="effort"]').fill('225');await page.locator('[data-control="effort"]').press('Tab');await page.locator('[data-lab="hold"]').click();
 // Reload within the mandatory minimum observation interval.
 await page.reload();await page.waitForSelector('#lab-navigation');const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')));assert.equal(data.trials.at(-1).interrupted,true);assert.equal(data.trials.at(-1).result,null);assert.equal(data.answers.Q13b.A.prediction,'Synthetic original prediction: extend effort to raise load.');assert.equal(await page.locator('#hold').innerText(),'Release');
 await page.locator('[data-lab="hold"]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')).trials.at(-1).settled);assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('lever-lab-notebook-v1')))).trials.length,2);
 // Pointer-authored strokes and keyboard Undo have independent evidence.
 await page.locator('#question-select').selectOption('1');await page.locator('#part-select').selectOption('Q1d');const surface=page.locator('.drawing-surface');await surface.scrollIntoViewIfNeeded();const box=await surface.boundingBox();await page.mouse.move(box.x+20,box.y+40);await page.mouse.down();await page.mouse.move(box.x+180,box.y+80,{steps:10});await page.mouse.up();assert.equal(await surface.locator('polyline').count(),1);await page.locator('[data-lab="sketch-undo"]').click();assert.equal(await surface.locator('polyline').count(),0);
 // Corrupt stored bytes remain available instead of being silently overwritten.
 const corrupt=await browser.newPage();await corrupt.addInitScript(()=>localStorage.setItem('lever-lab-notebook-v1','{"schema":999,"unreadableWork":"retain these bytes"}'));await corrupt.goto(origin);await corrupt.waitForSelector('#lab-navigation');assert.equal(await corrupt.locator('#save-status').innerText(),'Unreadable Save Kept');assert.equal(await corrupt.evaluate(()=>localStorage.getItem('lever-lab-notebook-v1')),'{"schema":999,"unreadableWork":"retain these bytes"}');await corrupt.locator('[data-lab="session"]').click();assert.equal(await corrupt.locator('[data-lab="recovery"]').isVisible(),true);
 // The new notebook imports the separate local Free Play arrangement on first use.
 const free=await browser.newPage();await free.addInitScript(()=>localStorage.setItem('lever-lab-v1',JSON.stringify({state:{load:-175,fulcrum:-75,effort:125,loadMass:300,effortMass:150},held:true,showMath:false,reduced:false})));await free.goto(origin);await free.waitForSelector('#lab-navigation');assert.equal(await free.locator('#mass-load').inputValue(),'300');assert.equal(await free.locator('#fulcrum-position').inputValue(),'-75');await free.locator('#swap').click();await free.locator('#swap').click();assert.equal(await free.locator('#distance-load').inputValue(),'100');assert.equal(await free.locator('#distance-effort').inputValue(),'200');
 assert.deepEqual(errors,[]);const manifest=JSON.parse(await readFile('dist/build-manifest.json','utf8'));await mkdir('artifacts/recovery-review',{recursive:true});await writeFile('artifacts/recovery-review/verification.json',JSON.stringify({build:manifest.id,passed:true,checks:['Interrupted release preserved on reload','Original prediction retained','Retry produces separate settled trial','Pointer sketch and Undo','Corrupt autosave kept for recovery','Separate Free Play state retained','Two swaps preserve off-center arms']},null,2));console.log('RECOVERY BROWSER PASSED '+manifest.id);
}finally{await browser?.close();server.kill();}
