import { readFile,writeFile,mkdir,cp,copyFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
const manifest=JSON.parse(await readFile('artifacts/current-build.json','utf8'));
const source=path.resolve('artifacts/builds',manifest.id),destination=path.resolve('artifacts/review-packages',manifest.id);
await mkdir(destination,{recursive:true});await cp(source,destination,{recursive:true});
await cp('artifacts/notebook-review',path.join(destination,'review'),{recursive:true});
await copyFile('THIRD_PARTY_NOTICES.md',path.join(destination,'THIRD_PARTY_NOTICES.md'));
const server=`import http from 'node:http';\nimport {readFile} from 'node:fs/promises';\nimport path from 'node:path';\nimport {fileURLToPath} from 'node:url';\nconst root=path.dirname(fileURLToPath(import.meta.url)),port=Number(process.env.PORT||4199);\nconst types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png'};\nhttp.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const relative=decodeURIComponent(url.pathname);const file=path.resolve(root,'.'+relative+(relative.endsWith('/')?'index.html':''));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}const data=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'}).end(data);}catch{res.writeHead(404).end('Not found');}}).on('error',e=>{console.error('Could not start local review:',e.message,'Choose another PORT if this one is occupied.');process.exitCode=1;}).listen(port,'127.0.0.1',()=>console.log('Open http://127.0.0.1:'+port+'/  |  Build ${manifest.id}'));\n`;
await writeFile(path.join(destination,'serve-review.mjs'),server);
await writeFile(path.join(destination,'START-HERE.txt'),`Lever Lab: Partners In Balance\nEARLY REVIEW — Q1–Q4 browser slice passed; full coverage verification continues.\n\nBuild: ${manifest.id}\nOriginal source baseline: 9bfce52767e51ae728ffa9fec717264c554d026b\n\n1. Extract this complete ZIP.\n2. With Node.js 22 or later installed, open a terminal in the extracted folder.\n3. Run: node serve-review.mjs\n4. Open http://127.0.0.1:4199/ in your browser.\n\nKeep the terminal open while reviewing. Press Ctrl+C when done. No npm install or internet is required. If this port is occupied, choose another PORT; browser saves are tied to the address, so download a backup before switching. Do not double-click index.html.\n\nTry Free Play, Learn, and Challenge Q1–Q4 first. Use Partners & Saves for pair/solo mode, role swaps, backup/restore, and Student Work download. The HTML report is printable and contains drawings and history. This is local review, not a deployment or a classroom readiness claim.\n\nKnown limits of this early review: the complete 68-row inventory is implemented but Q5–Q14 and complete paired/solo runs are still under verification. The floating notebook may cover labels; scroll to See Workbench to collapse it.\n\nScreenshots and exact tested scope are in review/. Test fixtures use fictional learner labels only.\n`);
await mkdir('output',{recursive:true});
// Python's standard-library zipfile keeps this packaging step dependency-free.
const python=process.env.REVIEW_PYTHON||'python';
execFileSync(python,['-c',"import pathlib,sys,zipfile; root=pathlib.Path(sys.argv[1]); out=pathlib.Path(sys.argv[2]); z=zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED); [z.write(p,p.relative_to(root.parent)) for p in root.rglob('*') if p.is_file()]; z.close()",destination,path.resolve('output',manifest.id+'.zip')]);
console.log(path.resolve('output',manifest.id+'.zip'));
