// Original digital wording for the owner's R06 packet tasks. Teacher source files
// stay outside the public game. IDs preserve the complete agreed coverage map.
const n=(key,label,answer)=>({key,label,type:'number',answer});
const c=(key,label,options,answer)=>({key,label,type:'select',options,answer});
const r=(key,label)=>({key,label,type:'text',personal:true,review:true});
const p=(key,label)=>({...r(key,label),type:key==='predictedMass'?'number':'text',review:false,prediction:true});
const motion=(key='observation')=>c(key,'What Did You Observe?',['Level','Load Side Down','Effort Side Down']);
const s=(lm,em,la,ea,f=0)=>({loadMass:lm,effortMass:em,load:f-la,effort:f+ea,fulcrum:f});
const part=(id,title,lesson,fields=[],extra={})=>({id,title,lesson,fields,...extra});
const sketch=(id,title,lesson)=>part(id,title,lesson,[{key:'drawing',label:'Your Labeled Lever Sketch',type:'sketch',personal:true,review:true}]);
const predict=(id,lesson,label='Predict what will happen and explain why.')=>part(id,'Predict Before Testing',lesson,[p('prediction',label)]);
const trial=(id,title,lesson,initial,allowed,prediction,extra={})=>part(id,title,lesson,[motion(),r('notes','Describe what you saw. Include any changes you made.')],{initial,allowed,trial:true,prediction,...extra});
const setup=(id,title,lesson,initial,target,allowed,extra={})=>part(id,title,lesson,[],{initial,target,allowed,setup:true,...extra});
const productFields=(prefix='')=>[n(prefix+'loadMass','Load Mass (g)'),n(prefix+'loadArm','Load Arm (mm)'),n(prefix+'loadProduct','Load Product (g·mm)'),n(prefix+'effortMass','Effort Push (g-equivalent)'),n(prefix+'effortArm','Effort Arm (mm)'),n(prefix+'effortProduct','Effort Product (g-equivalent·mm)')];
const eq=s(200,200,100,100), q5=s(400,200,100,200), q9=s(200,100,100,200), q10=s(300,150,150,150);
export const QUESTIONS=[
 {number:1,title:'Identify The Parts',page:'Part 1 · Page 1',parts:[
  part('Q1a','What We Lift','T1',[c('role','Which Role Is The Object We Want To Lift?',['Load','Effort','Fulcrum'],'Load')]),
  part('Q1b','The Input Force','T1',[c('role','Which Role Does The Pressing Hand Supply?',['Load','Effort','Fulcrum'],'Effort')]),
  part('Q1c','The Pivot','T1',[c('role','What Does The Beam Turn Around?',['Load','Effort','Fulcrum'],'Fulcrum')]),
  sketch('Q1d','Sketch And Label The Lever','T1')]},
 {number:2,title:'Measure From The Fulcrum',page:'Part 1 · Page 2',parts:[
  setup('Q2a','Prepare The Unequal Arms','T2',s(200,100,100,200),s(200,200,100,150),['loadMass','effortMass','load','effort','fulcrum'],{instructions:'Reset for this new investigation. Set load 200 g at 100 mm left of the centered fulcrum and effort push 200 g-equivalent at 150 mm right.'}),
  part('Q2b','Label Both Arm Distances','T2',[n('loadArm','Load Arm Label (mm)',100),n('effortArm','Effort Arm Label (mm)',150)]),
  part('Q2c','A Gap Or An Arm?','T2',[c('agree','Someone Calls The 250 mm Object Gap The Effort Arm. Do You Agree?',['Agree','Disagree'],'Disagree'),c('start','Effort Arm Begins At',['Load','Fulcrum','Effort'],'Fulcrum'),c('end','Effort Arm Ends At',['Load','Fulcrum','Effort'],'Effort'),r('reason','Explain the endpoints and why the whole gap is different.')])]},
 {number:3,title:'Equal Forces And Arms',page:'Part 1 · Page 2',parts:[
  setup('Q3a','Move Only The Effort Inward','T3',s(200,200,100,150),eq,['effort'],{instructions:'Hold level. Move only the effort 50 mm closer to the fulcrum. Load mass, effort push, and other positions stay fixed.'}),
  predict('Q3b','T3'), trial('Q3c','Release And Record','T3',eq,[],'Q3b'),
  part('Q3d','What Is Equal?','T3',[n('mass','Load Grams / Effort g-Equivalent',200),n('arm','Arm On Each Side (mm)',100),r('reason','Describe what is equal on the two sides.')])]},
 {number:4,title:'Change Only Load Mass',page:'Part 1 · Page 3',parts:[
  setup('Q4a','Double The Load Mass','T3',eq,s(400,200,100,100),['loadMass'],{instructions:'Keep Q3 positions and effort push. Change only the load mass from 200 g to 400 g.'}),
  predict('Q4b','T3','Which object will move down? Explain your prediction.'),
  trial('Q4c','Test The Heavier Load','T3',s(400,200,100,100),[],'Q4b'),
  part('Q4d','Record The Controlled Change','T3',[c('changed','Quantity Changed',['Load Mass','Effort Push','Load Arm','Effort Arm'],'Load Mass'),n('from','From (g)',200),n('to','To (g)',400),n('effortMass','Effort Push Kept (g-equivalent)',200),n('loadArm','Load Arm Kept (mm)',100),n('effortArm','Effort Arm Kept (mm)',100),c('fulcrum','Fulcrum Position',['Stayed Fixed','Changed'],'Stayed Fixed')])]},
 {number:5,title:'Balance By Moving Effort',page:'Part 1 · Page 4',parts:[
  setup('Q5a','Lengthen Only The Effort Arm','T4',s(400,200,100,100),q5,['effort'],{instructions:'Keep the 400 g load at 100 mm and the 200 g-equivalent effort push. Move only effort to a 200 mm arm.'}),
  trial('Q5b','Predict, Release, And Observe','T4',q5,[],true,{fields:[p('prediction','Predict the result before releasing.'),motion(),r('notes','Record what happened.')]}),
  part('Q5c','What Changed?','T4',[c('added','Did You Increase The Effort Push?',['Yes','No'],'No'),n('from','Effort Arm Before (mm)',100),n('to','Effort Arm After (mm)',200),r('reason','Explain what changed instead of push strength.')]),
  part('Q5d','Must The Load Move Down?','T4',[c('always','Must A Load With Greater Weight Than The Effort Push Move Down?',['Yes','No'],'No'),r('evidence','Use this trial as evidence for your claim.')])]},
 {number:6,title:'Balance By Changing Effort Push',page:'Part 1 · Page 4',parts:[
  trial('Q6a','Find Balance With Fixed Positions','T4',s(400,200,100,100),['effortMass'],false,{goal:'balance',instructions:'Keep both arms at 100 mm and the load at 400 g. Hold before each retry; change only effort push.'}),
  part('Q6b','Record Your Balancing Push','T4',[n('mass','Effort Push That Balanced (g-equivalent)',400)],{requiresTrial:'Q6a'}),
  part('Q6c','Compare Two Ways','T4',[c('q5','Q5 Changed',['Effort Position','Effort Push'],'Effort Position'),c('q6','Q6 Changed',['Effort Position','Effort Push'],'Effort Push'),r('reason','Explain two ways to balance the same load using Q5 and Q6.')])]},
 {number:7,title:'Investigate Effort Distance',page:'Part 1 · Page 5',parts:[
  setup('Q7a','Keep The Load Fixed','T3',s(200,100,100,200),s(300,100,100,200),['loadMass'],{instructions:'Reset. Keep the load at 100 mm and fulcrum at 0 mm. Set the load to 300 g; each following row changes only effort push at its prescribed arm.'}),
  ...[75,100,150,200].map((arm,i)=>trial('Q7b'+(i+1),`Effort Arm ${arm} mm`,'T4',s(300,100,100,arm),['effortMass'],true,{goal:'balance',tableRow:arm,fields:[p('predictedMass','Predict A Balancing Effort Push (g-equivalent)'),motion(),n('finalMass','Effort Push That Balanced (g-equivalent)',30000/arm)]})),
  part('Q7c','Describe The Trend','T4',[c('trend','Farther Effort Needs',['Less Push','The Same Push','More Push'],'Less Push'),r('reason','Explain the trend using your trials.')]),
  part('Q7d','When The Arm Doubles','T4',[n('near','Your Effort Push At 100 mm (g-equivalent)',300),n('far','Your Effort Push At 200 mm (g-equivalent)',150),c('ratio','Doubling The Arm Makes The Required Push',['Half As Much','Twice As Much','Unchanged'],'Half As Much'),r('reason','Compare your 100 mm and 200 mm rows. Use your values.')],{references:['Q7b2','Q7b4']})]},
 {number:8,title:'Investigate Load Distance',page:'Part 1 · Page 6',parts:[
  setup('Q8a','Keep Effort Distance Fixed','T3',s(200,100,100,200),s(200,100,100,200),[],{instructions:'Reset. Keep the load at 200 g, effort arm at 200 mm, and fulcrum at 0 mm.'}),
  ...[100,150,200].map((arm,i)=>trial('Q8b'+(i+1),`Load Arm ${arm} mm`,'T5',s(200,100,arm,200),['effortMass'],true,{goal:'balance',tableRow:arm,fields:[p('predictedMass','Predict A Balancing Effort Push (g-equivalent)'),motion(),n('finalMass','Effort Push That Balanced (g-equivalent)',arm)]})),
  part('Q8c','Describe The Load-Arm Trend','T5',[c('trend','Farther Load Needs',['Less Effort Push','The Same Effort Push','More Effort Push'],'More Effort Push'),r('reason','Explain the trend from your rows.')]),
  part('Q8d','Position, Mass, And Weight','T5',[c('changed','Moving The Load Changes',['Its Mass','Its Weight','Its Arm Distance'],'Its Arm Distance'),r('reason','Explain whether moving the load changed its mass or weight, and describe the position change.')]),
  part('Q8e','What Stayed Fixed?','T3',[c('constants','Choose The Held-Constant Quantities',['Load Mass, Effort Arm, Fulcrum','Load Arm, Effort Push, Fulcrum','Both Arm Distances'],'Load Mass, Effort Arm, Fulcrum')])]},
 {number:9,title:'Swap Positions',page:'Part 2 · Page 1',parts:[
  trial('Q9a','Check Balance Before Swapping','T6',q9,[],false,{goal:'balance',instructions:'Reset to load 200 g at 100 mm and effort push 100 g-equivalent at 200 mm, fulcrum 0. Release to check balance, then hold level.'}),
  part('Q9b','Predict Before Swap','T6',[p('mass','Will the load mass or effort push change?'),p('roles','Will the hanging load and hand exchange roles?'),p('balance','Will it still balance?')]),
  setup('Q9c','Swap And Label The New Arms','T6',q9,{...q9,load:200,effort:-100},['load','effort'],{swap:true,prediction:'Q9b',fields:[n('loadArm','New Load Arm Label (mm)',200),n('effortArm','New Effort Arm Label (mm)',100)],instructions:'Hold level, then use Swap Positions. The load keeps its mass, the hand keeps its push setting, and both keep their roles.'}),
  trial('Q9d','Release The Swapped Lever','T6',{...q9,load:200,effort:-100},[],'Q9b'),
  part('Q9e','Explain The Result','T6',[r('reason','Use the two arrangements to explain why the result changed or stayed the same.')])]},
 {number:10,title:'Move The Fulcrum',page:'Part 2 · Page 2',parts:[
  part('Q10a','Find Beam Position','T7',[c('coordinate','A Negative Beam Position Is',['Left Of Center','Right Of Center','A Negative Arm Length'],'Left Of Center')],{instructions:'Select Side View and open Controls. Find Beam Position in the Fulcrum panel. Coordinates are signed; arm lengths stay positive.'}),
  trial('Q10b','Test The Centered Fulcrum','T7',q10,[],true,{fields:[p('prediction','Predict the centered result.'),motion(),r('notes','Record the centered result.')]}),
  setup('Q10c','Move Only The Fulcrum','T7',q10,{...q10,fulcrum:-50},['fulcrum'],{instructions:'Hold. Keep both application coordinates, load mass, and effort push fixed. Change only fulcrum Beam Position to -50 mm.'}),
  part('Q10d','Measure Both New Arms','T7',[n('loadArm','New Load Arm Label (mm)',100),n('effortArm','New Effort Arm Label (mm)',200),n('gap','Distance Between Objects (mm)',300)]),
  trial('Q10e','Predict And Test The Shifted Pivot','T7',{...q10,fulcrum:-50},[],true,{fields:[p('prediction','Predict the result after moving the fulcrum.'),motion(),r('notes','Record the result.')]}),
  part('Q10f','One Support, Two Arms','T7',[r('reason','Explain how moving one support changed both arms while the object gap stayed fixed.')])]},
 {number:11,title:'Find A Numerical Pattern',page:'Part 2 · Page 3',parts:[
  part('Q11a','Calculate The Q5 Products','T8',productFields(),{products:q5,instructions:'No new test is needed. Use Q5: load 400 g at 100 mm; effort push 200 g-equivalent at 200 mm. Multiply the load grams and effort g-equivalent by their own arms.'}),
  part('Q11b','Compare The Products','T8',[c('compare','The Two Q5 Products Are',['Equal','Different'],'Equal'),r('reason','What do you notice about the products?')]),
  part('Q11c','Choose Your Own Q7 Trial','T8',[c('trialId','Your Balanced Q7 Row',[]),...productFields()],{priorTrial:true,instructions:'Choose any balanced trial you actually recorded in Q7. If none is saved, return to Q7 and recreate one. No example will be invented for you.'}),
  part('Q11d','State Your Balance Rule','T8',[c('rule','The Balance Equation',['Load Mass × Load Arm = Effort Push × Effort Arm','Load Mass + Load Arm = Effort Push + Effort Arm','Load Mass = Effort Push'],'Load Mass × Load Arm = Effort Push × Effort Arm'),r('reason','Write your rule in your own words. Explain how load weight, effort push, and arm distance work together.')])]},
 {number:12,title:'Ideal Mechanical Advantage',page:'Part 2 · Page 4',parts:[
  ...[[100,100,1],[100,200,2],[200,100,.5]].map(([la,ea,answer],i)=>part('Q12'+String.fromCharCode(97+i),`IMA: ${la} mm Load / ${ea} mm Effort`,'T9',[n('ima','IMA (No Unit)',answer)],{instructions:`Calculate effort arm ÷ load arm, with matching units. Load arm ${la} mm; effort arm ${ea} mm.`})),
  part('Q12d','Compare Effort Force With Load Weight','T9',[[100,100,'Equal To'],[100,200,'Less Than'],[200,100,'Greater Than']].map(([la,ea,a],i)=>c('row'+(i+1),`At Ideal Balance (${la} mm Load, ${ea} mm Effort), Effort Force Is ___ The Load’s Weight`,['Less Than','Equal To','Greater Than'],a))),
  part('Q12e','Choose The Least Effort','T9',[c('row','For The Same Load, Which Needs Least Effort?',['100 mm Load / 100 mm Effort','100 mm Load / 200 mm Effort','200 mm Load / 100 mm Effort'],'100 mm Load / 200 mm Effort'),r('reason','Explain your choice.')]),
  part('Q12f','First Class And Force Advantage','T9',[c('guarantee','Does First Class Guarantee IMA Greater Than 1?',['Yes','No'],'No'),r('reason','Explain what first class tells you and what determines IMA.')])]},
 {number:13,title:'Balance, Then Raise The Load',page:'Part 2 · Page 5',parts:[
  trial('Q13a','Find The Balancing Effort Arm','T10',s(400,200,100,100),['effort'],false,{goal:'balance',fields:[motion(),n('arm','Effort Arm That Balances (mm)',200),n('loadLabel','Starting Diagram Load Arm Label (mm)',100),n('effortLabel','Balanced Diagram Effort Arm Label (mm)',200)],instructions:'Reset. Keep load 400 g at 100 mm, effort push 200 g-equivalent, fulcrum 0. Change only effort arm; hold before every retry.'}),
  predict('Q13b','T10','Predict a distance change that will raise the load and explain why.'),
  trial('Q13c','Try Your Lifting Change','T10',q5,['effort'],'Q13b',{goal:'effort',fields:[motion(),n('arm','An Effort Arm That Raised The Load (mm)')],instructions:'Hold level. Change only effort arm, then release. With fulcrum centered, no object can exceed 250 mm from the center.'}),
  part('Q13d','Balance Versus Rising','T10',[r('reason','Explain the difference between balancing the load and making it rise.')])]},
 {number:14,title:'Design And Defend',page:'Part 2 · Page 6',parts:[
  setup('Q14a','Choose A Constrained Design','T11',s(200,100,100,200),null,['load','effort','loadMass','effortMass'],{design:true,fields:[n('loadMass','Chosen Load Mass (g)'),n('effortMass','Chosen Effort Push (g-equivalent)'),n('loadArm','Chosen Load Arm (mm)'),n('effortArm','Chosen Effort Arm (mm)')],instructions:'Reset. Keep fulcrum at 0 mm. Choose a load mass in grams at least twice the effort push setting in g-equivalent and a geometry you expect to balance. Hold before every adjustment.'}),
  sketch('Q14b','Draw And Label Your Design','T11'),
  part('Q14c','Defend Before Release','T11',[n('loadProduct','Predicted Load Product (g·mm)'),n('effortProduct','Predicted Effort Product (g-equivalent·mm)'),p('prediction','Use your Q11 rule to explain why your design should balance.')],{designPrediction:true}),
  trial('Q14d','Test And Revise Your Design','T11',null,['load','effort','loadMass','effortMass'],'Q14c',{goal:'balance',design:true,fields:[motion(),r('notes','Record the result and each change you made. Hold before retrying.')],instructions:'Use your own Q14 design. Your original prediction stays saved. Record any revisions.'}),
  part('Q14e','Make A Claim With Evidence','T11',[r('claim','Complete: A smaller effort force can balance a larger load when…'),r('evidence','My evidence from my own design and test is…')],{references:['Q14d']})]}
];
export const PARTS=QUESTIONS.flatMap(q=>q.parts.map(item=>({...item,question:q.number,page:q.page})));
export const PART_BY_ID=Object.fromEntries(PARTS.map(p=>[p.id,p]));
export const LESSONS=[
 ['T0','Use The Workbench','Open Controls to enter a number, slide a control, or halve/double a value. Load mass is in g; effort push is in g-equivalent; arms are in mm. Values snap to steps of 25. Hold Level before edits, hide math before predictions, then Release and wait. Buttons name their next action; the status names the current state. Reset only when directed. Load Side Down follows the hanging load, even after a swap.', 'Try: Hold Level, change effort push by one step, release, then hold again. Watch the explicit status.',s(200,100,100,200)],
 ['T1','Roles And Labeled Sketches','The load is what you want to lift. The hanging load has weight from gravity. The hand supplies a downward effort push. Push is a force, not hand mass. The fulcrum is the pivot between them: a first-class arrangement. Create your own sketch using strokes or the keyboard diagram builder, add labels, and use Undo to revise.', 'Try: In the practice sketch, add a beam and choose positions for load, fulcrum, and effort. Label all three.',s(250,125,100,200)],
 ['T2','Measure From The Pivot','An arm begins at the fulcrum and ends at that role’s force location. It is a positive length. A beam coordinate is signed: negative left of center, positive right. The gap between objects includes both arms.', 'Try: Put load at −100 mm, fulcrum at 0, effort at +150 mm. The effort arm is 150 mm; the whole gap is 250 mm.',s(200,200,100,150)],
 ['T3','Make A Fair Test','Change only the named quantity. Keep a prediction before seeing the outcome. Predictions are evidence of thinking, not wrong answers. Release from held level. Observe, record, hold again, and revise. A moving beam passing through level is not yet balanced.', 'Try: Start with equal 100 mm arms and 150 g masses. Change only load mass to 300 g. Predict, then test.',s(150,150,100,100)],
 ['T4','Trade Effort Push For Distance','For a fixed load and load arm, moving the hand farther away reduces the effort push needed for balance. Doubling its arm halves the required push. You can instead keep positions fixed and change effort push.', 'Try: Balance a 250 g load at 100 mm with effort at 200 mm. Then halve the effort arm and find a new balancing push.',s(250,125,100,200)],
 ['T5','Move The Load','For a fixed load mass and effort arm, a longer load arm requires more effort push. Moving the load changes its distance, not its mass or weight.', 'Try: Keep load 150 g and effort arm 150 mm. Compare balancing effort with load arms 100 mm and 200 mm.',s(150,100,100,150)],
 ['T6','Swap Without Changing Roles','Swap Positions exchanges object coordinates. The load keeps its mass and the hand keeps its calibrated push. Both keep their roles. Hold level first. The load may now be on the right; name motion by role, not screen direction. Swapping twice restores the original coordinates.', 'Try: Predict, swap, and test a balanced unequal-arm arrangement. Hold and swap a second time.',s(250,125,100,200)],
 ['T7','Move One Support','Use Side View. Fulcrum Beam Position is measured from beam center. Negative is toward the marked left end. Moving only the fulcrum changes both arms while application coordinates, load mass, effort push, and gap stay fixed.', 'Try: Keep objects at −150 and +150 mm; move fulcrum from 0 to −50 mm. Compare both positive arms.',s(200,100,150,150)],
 ['T8','Products And Saved Trials','Multiply the load grams and effort g-equivalent by their own arms. Equal opposing products predict balance from level in this model. g·mm is a mass-distance comparison, not SI torque. Select a real saved balanced Q7 row when you test your rule again; preserve the link to that trial.', 'Try: Calculate 250 g × 100 mm and 125 g × 200 mm. Record a Q7 trial, then locate it in Q11.',s(250,125,100,200)],
 ['T9','IMA And Required Force','IMA = effort arm ÷ load arm. Matching distance units cancel. At ideal balance, effort force = load weight ÷ IMA, so IMA 2 needs half the load’s weight as effort; IMA 0.5 needs twice. First class describes the middle fulcrum and does not guarantee IMA above 1. Do not apply the ideal-balance force equality to an arbitrary unbalanced trial.', 'Try: Compare equal arms, twice-as-long effort arm, and twice-as-long load arm. Calculate each arm ratio.',s(250,125,100,200)],
 ['T10','Balance And Begin Lifting','Equal opposing products keep a lever released from level balanced. A greater effort-side product starts raising the load. Stay inside the legal coordinate limits; a centered arm cannot exceed 250 mm.', 'Try: With load 250 g at 100 mm and effort push 125 g-equivalent at 200 mm, test balance. Hold; move effort to 225 mm; test again.',s(250,125,100,200)],
 ['T11','Design, Test, And Defend','Choose a centered arrangement with load mass at least twice effort push. Label all masses and arms in your own drawing. Predict using products, release, record, then revise from level if needed. Use your actual trial as evidence.', 'Try: Create a different balanced arrangement and explain how a smaller effort compensates with a longer arm. This simulation prepares for physical selection and explanation; real building and testing remain separate.',s(300,100,75,225)],
 ['T12','Progress And Downloads','Work together on one anonymous classwork notebook, or work independently. Your teacher guides any changes of roles. Classwork saves in this browser; Question Index offers Recover Saved Work for a portable recovery copy. No account or student name is required here.', 'Try: Record a response and locate Recover Saved Work in Question Index. After every question has its required evidence, download the completed work. Attach it to Google Classroom and choose Turn In. Downloading does not upload or verify submission.',s(200,100,100,200)]
].map(([id,title,text,practice,initial])=>({id,title,text,practice,initial}));
export const REQUIRED_IDS=['Intro','Routine',...PARTS.map(p=>p.id)];
