import { PARTS,PART_BY_ID,QUESTIONS,LESSONS } from './curriculum.js';
import { DEFAULT,valid,arm,setMass,setDistance,move,measures,restingAngle,balanceStatus } from './model.js';
import { NOTEBOOK_KEY,MAX_BACKUP_BYTES,loadNotebook,saveNotebook,parseBackup,answer,response,learners,stamp,event,rotate,visitLesson,predictionReady,snapshot,latestTrial,checkPart,coverage,invalidateChecks,sameState,supportViewed,revalidateChecks } from './notebook.js';
import {escapeHTML as esc,drawingSVG,reportHTML} from './report.js';
import {emphasizeTerms,vocabularyReference} from './reference.js';
const $=s=>document.querySelector(s);
const button=(action,label,extra='')=>`<button data-lab="${action}" ${extra}>${label}</button>`;
const options=(values,value)=>values.map(v=>`<option value="${esc(typeof v==='object'?v.value:v)}" ${String(typeof v==='object'?v.value:v)===String(value)?'selected':''}>${esc(typeof v==='object'?v.label:v)}</option>`).join('');
export function mountLearning(app){
 let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error('Browser storage is unavailable.');},setItem(){throw Error();}};}
 const loaded=loadNotebook(storage,$('#build-identity').textContent);let book=loaded.book,manifest=null,pending=null,changes=[],initializing=false,saveError=loaded.error,recoveryRaw=loaded.recovery;
 if(loaded.fresh)book.freeWorkbench=snapshot(app.get().state,app.get().held);
 const drafts=new Map();
 fetch('./build-manifest.json').then(r=>r.json()).then(x=>manifest=x).catch(()=>{});
 for(const t of book.trials)if(!t.completedAt){t.interrupted=true;t.completedAt=stamp();}
 const nav=document.createElement('nav');nav.id='lab-navigation';nav.setAttribute('aria-label','Learning Modes');nav.innerHTML=`${button('mode-free','Free Play')}${button('mode-learn','Learn')}${button('mode-challenge','Challenge')}${button('session','Partners & Saves')}<span id="role-status"></span><output id="save-status" role="status"></output>`;$('#top').append(nav);
 const pane=document.createElement('aside');pane.id='notebook';pane.setAttribute('aria-label','Learning Notebook');document.querySelector('#app').append(pane);
 const reopen=document.createElement('button');reopen.id='notebook-reopen';reopen.textContent='Open Notebook';reopen.hidden=true;reopen.onclick=()=>{pane.hidden=false;reopen.hidden=true;};$('#app').append(reopen);
 const modal=document.createElement('dialog');modal.id='session-dialog';modal.innerHTML='<h2>Partners And Saves</h2><div id="session-body"></div>';$('#app').append(modal);
 function persist(){if(recoveryRaw){$('#save-status').textContent='Unreadable Save Kept';return;}const saved=saveNotebook(storage,book);saveError=saved.ok?saveError:saved.error;$('#save-status').textContent=saveError?'Backup Needed':'Saved On This Device';$('#save-status').title=saveError??'Progress stays in this browser. Download a backup before changing devices.';}
 function tell(message){app.notice(message);const out=$('#lab-feedback');if(out)out.textContent=message;}
 function status(){const names=Object.fromEntries(book.team.learners.map(l=>[l.id,l.label]));$('#role-status').textContent=book.team.mode==='pair'?`Driver: ${names[book.team.driver]} · Navigator: ${names[book.team.driver==='A'?'B':'A']}`:`Solo: ${names.A}`;for(const m of ['free','learn','challenge'])nav.querySelector(`[data-lab="mode-${m}"]`).setAttribute('aria-pressed',String(book.mode===m));}
 function flushDrafts(){for(const d of drafts.values()){const current=answer(book,d.id,d.key,d.owner);if(JSON.stringify(current)!==JSON.stringify(d.previous))book.history.push({id:d.id,key:d.key,owner:d.owner,value:structuredClone(current),previous:d.previous,at:stamp(),driver:d.driver});}drafts.clear();}
 function storeWorkbench(){flushDrafts();if(initializing)return;const w=snapshot(app.get().state,app.get().held);if(book.mode==='challenge')book.workbenches[book.part]=w;else if(book.mode==='free')book.freeWorkbench=w;}
 function loadWorkbench(w){initializing=true;app.load(w);initializing=false;}
 function interrupt(){if(pending){pending.interrupted=true;pending.settled=false;pending.result=null;pending.completedAt=stamp();event(book,'trial-interrupted',{trialId:pending.id});pending=null;app.hold();}}
 function selectPart(id,preserveCurrent=true){interrupt();if(preserveCurrent)storeWorkbench();book.mode='challenge';book.part=id;changes=[];const part=PART_BY_ID[id];let w=book.workbenches[id];if(!w){let state=part.initial;if(part.design||part.designPrediction||id==='Q14b')state=book.workbenches.Q14a?.state??state;
   if(!state){const index=PARTS.findIndex(p=>p.id===id);const prior=PARTS.slice(0,index).reverse().find(p=>p.question===part.question&&(book.workbenches[p.id]||p.target||p.initial));state=prior?(book.workbenches[prior.id]?.state??prior.target??prior.initial):DEFAULT;}
   w=snapshot(state,true);book.workbenches[id]=w;
  }loadWorkbench({...w,held:true});book.workbenches[id].held=true;app.math(false);render();pane.scrollTop=0;persist();}
 function enterMode(mode){if(mode==='learn')return goLesson(book.lesson,book.mode==='challenge'?book.part:book.returnTo);interrupt();storeWorkbench();if(mode==='challenge'){selectPart(book.part,false);return;}book.mode=mode;book.returnTo=null;loadWorkbench(book.freeWorkbench);pane.hidden=true;reopen.hidden=true;render();persist();}
 function resumeNotebook(){revalidateChecks(book);if(book.mode==='challenge')selectPart(book.part,false);else{loadWorkbench(book.mode==='free'?book.freeWorkbench:snapshot(LESSONS.find(l=>l.id===book.lesson).initial));if(book.mode==='learn')supportViewed(book,'lesson',book.lesson);render();persist();}}
 function refreshCheckStatus(){if(book.mode!=='challenge')return;const check=book.checks[book.part];if(check?.status==='Needs Recheck'){const out=$('#lab-feedback');if(out)out.textContent='Needs Recheck: evidence changed. Save & Check again.';}const total=$('#coverage-count');if(total)total.textContent=coverage(book).filter(x=>x.complete).length;}
 function goLesson(id,from=null){interrupt();storeWorkbench();visitLesson(book,id,from);loadWorkbench(snapshot(LESSONS.find(l=>l.id===id).initial));app.math(false);render();pane.scrollTop=0;persist();}
 function simulator(part){const w=app.get(),s=w.state,allowed=book.mode==='learn'?['loadMass','effortMass','load','effort','fulcrum']:(part?.allowed??[]);return `<details class="mini-controls" open><summary>Workbench Controls</summary><p class="state-note">${esc(w.held?'Held Level':'Released')} · Math ${app.mathVisible()?'Visible':'Hidden'} · Mass g / Distance mm</p><div class="lab-controls">${[['loadMass','Load Mass (g)',s.loadMass],['effortMass','Effort Mass (g)',s.effortMass],['load','Load Arm (mm)',arm(s,'load')],['effort','Effort Arm (mm)',arm(s,'effort')],['fulcrum','Fulcrum Position (mm)',s.fulcrum]].map(([key,label,value])=>`<label>${label}<input data-control="${key}" aria-label="Notebook ${label}" type="number" step="25" value="${value}" ${allowed.includes(key)?'':'disabled'}></label>`).join('')}</div><div class="button-row">${button('hold',w.held?'Release':'Hold Level')}${button('side','Side View')}${part?.swap||book.mode==='learn'?button('swap','Swap Positions'):''}</div><p class="lab-note">${book.mode==='challenge'?'Only the named variables can change. Hold level before adjusting.':'Practice changes do not alter your saved challenge arrangement.'}</p><output id="trial-state" aria-live="polite"></output></details>`;}
 function fieldHTML(part,f,owner){const v=answer(book,part.id,f.key,owner);let control;const attrs=`data-answer="${esc(f.key)}" data-owner="${owner}"`;
  if(f.type==='sketch')return sketchHTML(part.id,owner,v);
  let choices=f.options;
  if(f.key==='trialId')choices=book.trials.filter(t=>/^Q7b/.test(t.part)&&t.result==='balance'&&t.settled&&!t.interrupted).map(t=>({value:t.id,label:`${t.part} · ${t.setup.effortArm} mm · ${t.setup.state.effortMass} g · ${t.startedAt.slice(11,19)}`}));
  if(f.type==='select')control=`<select ${attrs}><option value="">Choose…</option>${options(choices,v)}</select>`;
  else if(f.type==='text')control=`<textarea ${attrs} rows="3" maxlength="10000">${esc(v)}</textarea>`;
  else control=`<input ${attrs} type="number" value="${esc(v)}" step="any">`;
  return `<label class="response-field">${esc(f.label)}${f.prediction?'<small>Saved before testing; prediction correctness is not graded.</small>':''}${f.review?'<small>Recorded for teacher review.</small>':''}${control}</label>`;
 }
 function sketchHTML(id,owner,value){return `<div class="sketch" data-sketch-owner="${owner}"><b>Your Own Labeled Sketch</b><div class="drawing-surface" tabindex="0" aria-label="Draw Your Lever Sketch">${drawingSVG(value||{elements:[]})}</div><p class="lab-note">Draw with a pointer, or build the entire diagram with the keyboard controls below. Add all three role labels. Undo removes your last addition.</p><div class="sketch-controls"><label>Component<select data-sketch-kind>${options(['beam','load','fulcrum','effort','label'],'beam')}</select></label><label>Horizontal Position<input data-sketch-x type="number" min="20" max="580" value="300"></label><label>Vertical Position<input data-sketch-y type="number" min="55" max="220" value="130"></label><label>Label<input data-sketch-label maxlength="100" placeholder="Role, mass, arm, or note"></label></div>${button('sketch-add','Add Component',`data-owner="${owner}"`)}${button('sketch-undo','Undo',`data-owner="${owner}"`)}</div>`;}
 function render(){status();if(book.mode==='free'){pane.hidden=true;reopen.hidden=true;return;}pane.hidden=false;reopen.hidden=true;
  if(book.mode==='learn'){const l=LESSONS.find(x=>x.id===book.lesson);pane.innerHTML=`<div class="notebook-heading"><h2>Learn</h2>${button('hide','See Workbench')}</div><label>Tutorial<select id="lesson-select">${options(LESSONS.map(x=>({value:x.id,label:x.id+' · '+x.title})),l.id)}</select></label><h3>${esc(l.title)}</h3><p>${emphasizeTerms(l.text)}</p><p class="practice-prompt"><b>Practice</b><br>${emphasizeTerms(l.practice)}</p>${vocabularyReference}${simulator(null)}${l.id==='T1'?sketchHTML('Q1d','A',book.tutorials.T1?.drawing):''}<label>What Did You Try Or Notice?<textarea id="lesson-note" rows="3">${esc(book.tutorials[l.id]?.note??'')}</textarea></label>${button('lesson-done','Record This Practice')}${book.returnTo?button('return','Return To '+book.returnTo):''}<output id="lab-feedback" role="status"></output>`;
  }else{const part=PART_BY_ID[book.part],q=QUESTIONS.find(q=>q.number===part.question),check=book.checks[part.id],index=PARTS.findIndex(p=>p.id===part.id);
   pane.innerHTML=`<div class="notebook-heading"><h2>Challenge</h2>${button('hide','See Workbench')}</div><label>Question<select id="question-select">${options(QUESTIONS.map(q=>({value:q.number,label:q.number+') '+q.title})),q.number)}</select></label><label>Subpart<select id="part-select">${options(q.parts.map(p=>({value:p.id,label:p.id+' · '+p.title})),part.id)}</select></label><p class="eyebrow">${esc(part.page)} · ${part.id}</p><h3 tabindex="-1" id="part-heading">${esc(part.title)}</h3>${part.instructions?`<p>${esc(part.instructions)}</p>`:''}${part.initial||part.setup||part.trial||part.designPrediction?simulator(part):''}${part.id==='Q10a'?button('side','Side View / Diagram'):''}${part.priorTrial?button('q7','Record Or Recreate A Q7 Trial'):''}${(part.references??[]).map(id=>`<details><summary>Saved Evidence: ${id}</summary><pre>${esc(JSON.stringify({responses:book.answers[id]??{},trial:latestTrial(book,id)??'No trial recorded'},null,2))}</pre></details>`).join('')}${part.fields.filter(f=>!f.personal).map(f=>fieldHTML(part,f,'shared')).join('')}${part.fields.some(f=>f.personal)?learners(book).map(l=>`<fieldset><legend>${esc(l.label)} · Your Own Thinking</legend>${part.fields.filter(f=>f.personal).map(f=>fieldHTML(part,f,l.id)).join('')}</fieldset>`).join(''):''}<div class="button-row">${button('check','Save & Check')}${button('help','Learn This · '+part.lesson)}</div><div id="lab-feedback" role="status">${check?`<b>${esc(check.status)}</b><ul>${[...check.failures,...check.missing].map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${check.review.length?'<p>Explanations and drawings stay marked for teacher review.</p>':''}`:''}</div><div class="button-row">${button('previous','Previous',index===0?'disabled':'')}${button('next','Next',index===PARTS.length-1?'disabled':'')}</div><p class="lab-note"><span id="coverage-count">${coverage(book).filter(x=>x.complete).length}</span> / ${coverage(book).length} evidence items recorded. This is not a mastery score. Explanations and drawings need teacher review.</p>`;
  }
  wireFields();wireSketches();
 }
 function wireFields(){pane.querySelectorAll('[data-answer]').forEach(input=>input.addEventListener('input',()=>{const key=book.part+'|'+input.dataset.owner+'|'+input.dataset.answer;if(!drafts.has(key))drafts.set(key,{id:book.part,key:input.dataset.answer,owner:input.dataset.owner,previous:structuredClone(answer(book,book.part,input.dataset.answer,input.dataset.owner)),driver:book.team.driver});response(book,book.part,input.dataset.answer,input.value,input.dataset.owner,false);refreshCheckStatus();persist();}));
  pane.querySelectorAll('[data-control]').forEach(input=>input.addEventListener('change',()=>{const s=app.get().state,k=input.dataset.control;app.change(k.endsWith('Mass')?setMass(s,k==='loadMass'?'load':'effort',input.value):k==='fulcrum'?move(s,k,input.value):setDistance(s,k,input.value));renderControls();}));
  $('#question-select')?.addEventListener('change',e=>selectPart(QUESTIONS.find(q=>q.number===Number(e.target.value)).parts[0].id));$('#part-select')?.addEventListener('change',e=>selectPart(e.target.value));$('#lesson-select')?.addEventListener('change',e=>goLesson(e.target.value,book.returnTo));
  $('#lesson-note')?.addEventListener('input',e=>{book.tutorials[book.lesson]??={};book.tutorials[book.lesson].note=e.target.value;persist();});
 }
 function renderControls(){const controls=pane.querySelector('.mini-controls');if(controls){controls.outerHTML=simulator(PART_BY_ID[book.part]);pane.querySelectorAll('[data-control]').forEach(input=>input.addEventListener('change',()=>{const s=app.get().state,k=input.dataset.control;app.change(k.endsWith('Mass')?setMass(s,k==='loadMass'?'load':'effort',input.value):k==='fulcrum'?move(s,k,input.value):setDistance(s,k,input.value));renderControls();}));}}
 function sketchSave(owner,drawing){if(book.mode==='learn'){book.tutorials.T1??={};book.tutorials.T1.drawing=drawing;}else response(book,book.part,'drawing',drawing,owner);refreshCheckStatus();persist();const surface=pane.querySelector(`[data-sketch-owner="${owner}"] .drawing-surface`);if(surface)surface.innerHTML=drawingSVG(drawing);}
 function wireSketches(){for(const container of pane.querySelectorAll('.sketch')){const surface=container.querySelector('.drawing-surface'),owner=container.dataset.sketchOwner;let points=null;
   const point=e=>{const r=surface.getBoundingClientRect();return [Math.max(0,Math.min(600,(e.clientX-r.left)*600/r.width)),Math.max(0,Math.min(280,(e.clientY-r.top)*280/r.height))];};
   surface.addEventListener('pointerdown',e=>{points=[point(e)];surface.setPointerCapture(e.pointerId);});surface.addEventListener('pointermove',e=>{if(points&&points.length<5000)points.push(point(e));});surface.addEventListener('pointerup',()=>{if(!points)return;const id=book.mode==='learn'?'Q1d':book.part;const d=structuredClone((book.mode==='learn'?book.tutorials.T1?.drawing:answer(book,id,'drawing',owner))||{elements:[]});d.elements.push({kind:'stroke',x:0,y:0,points,label:''});points=null;sketchSave(owner,d);});
  }}
 function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function session(){storeWorkbench();persist();$('#session-body').innerHTML=`<p>Use learner labels or names your teacher requests. They stay in this browser and in files you choose to download.</p><label>Working Mode<select id="team-mode">${options(['solo','pair'],book.team.mode)}</select></label>${book.team.learners.map(l=>`<label>${l.id==='A'?'Learner A':'Learner B'}<input id="learner-${l.id}" maxlength="80" value="${esc(l.label)}"></label>`).join('')}<label>Teacher-Controlled Reminder<select id="role-reminder">${options([{value:0,label:'Off — Teacher Calls Swaps'},{value:2,label:'2 Minutes'},{value:3,label:'3 Minutes'},{value:5,label:'5 Minutes'}],book.team.reminderMinutes)}</select></label><p>The reminder never swaps automatically. The teacher calls the change.</p><div class="button-row">${button('settings','Save Settings')}${button('roles','Swap Roles')}</div><h3>Keep Your Work</h3><p>${esc(saveError??'Autosave is local to this browser. Keep a downloaded backup too.')}</p>${recoveryRaw?button('recovery','Download Unreadable Save'):''}${button('backup','Download Backup JSON')}${button('report','Download Student Work')}<label>Restore Backup<input id="restore-backup" type="file" accept=".json,application/json"></label><p id="restore-preview"></p>${button('restore','Replace With Reviewed Backup','disabled')}<p>A restore replaces this open notebook after validation. Download a backup first if you need both sessions.</p><h3>Submit In Google Classroom</h3><p>Download Student Work, attach the file to your assignment, and select Turn In. Lever Lab does not upload or verify submission.</p>${button('close-session','Done')}<output id="session-feedback" role="status"></output>`;
  let candidate=null;$('#restore-backup').addEventListener('change',async e=>{candidate=null;modal.querySelector('[data-lab="restore"]').disabled=true;try{const file=e.target.files[0];if(!file||file.size>MAX_BACKUP_BYTES)throw Error('Choose a Lever Lab JSON backup smaller than 12 MB.');candidate=parseBackup(await file.text());$('#restore-preview').textContent=`Ready to restore ${candidate.team.learners.map(l=>l.label).join(' / ')} · ${candidate.history.length} revisions · saved ${candidate.updatedAt}`;modal.querySelector('[data-lab="restore"]').disabled=false;}catch(e){$('#restore-preview').textContent=e.message;}});
  modal.querySelector('[data-lab="restore"]').onclick=()=>{if(!candidate)return;interrupt();flushDrafts();book=candidate;changes=[];recoveryRaw=null;for(const t of book.trials)if(!t.completedAt){t.interrupted=true;t.completedAt=stamp();}candidate=null;saveError=null;modal.close();resumeNotebook();};modal.showModal();
 }
 function action(e){const b=e.target.closest('[data-lab]');if(!b)return;const a=b.dataset.lab;
  if(a.startsWith('mode-'))return enterMode(a.slice(5));
  if(a==='hide'){pane.hidden=true;reopen.hidden=false;return;}
  if(a==='session')return session();if(a==='close-session'){modal.close();return;}
  if(a==='settings'){flushDrafts();const oldMode=book.team.mode;book.team.mode=$('#team-mode').value;for(const l of book.team.learners)l.label=$('#learner-'+l.id).value.trim()||'Learner '+l.id;book.team.reminderMinutes=Number($('#role-reminder').value);book.team.rotationStarted=stamp();if(book.team.mode==='solo')book.team.driver='A';if(oldMode!==book.team.mode)for(const p of PARTS.filter(p=>p.fields.some(f=>f.personal)))delete book.checks[p.id];event(book,'session-settings',{team:book.team});persist();status();render();$('#session-feedback').textContent='Settings saved.';return;}
  if(a==='roles'){flushDrafts();rotate(book);persist();status();$('#session-feedback').textContent=book.team.mode==='pair'?'Roles swapped. The apparatus did not change.':'Solo mode keeps one learner.';return;}
  if(a==='recovery'){download('LeverLab-Unreadable-Save.json',recoveryRaw,'application/json');return;}
  if(a==='backup'){storeWorkbench();persist();download('LeverLab-Backup-'+book.id.slice(0,8)+'.json',JSON.stringify(book,null,2),'application/json');return;}
  if(a==='report'){storeWorkbench();persist();download('LeverLab-Student-Work-'+book.id.slice(0,8)+'.html',reportHTML(book,manifest),'text/html');return;}
  if(a==='hold'){app.toggleHold();renderControls();return;}if(a==='side'){app.side();return;}if(a==='swap'){app.swap();renderControls();return;}
  if(a==='help')return goLesson(PART_BY_ID[book.part].lesson,book.part);
  if(a==='return'){const id=book.returnTo;book.returnTo=null;return selectPart(id);}
  if(a==='q7')return selectPart('Q7b1');
  if(a==='lesson-done'){book.tutorials[book.lesson]={...book.tutorials[book.lesson],note:$('#lesson-note').value,completedAt:stamp(),driver:book.team.driver};if(book.lesson==='T0')book.coverage.Routine=true;if(['T0','T1','T2'].every(id=>book.tutorials[id]?.completedAt))book.coverage.Intro=true;persist();tell('Practice recorded. You can return to your challenge.');return;}
  if(a==='check'){storeWorkbench();checkPart(book,PART_BY_ID[book.part],app.get());persist();render();return;}
  if(a==='next'||a==='previous'){const i=PARTS.findIndex(p=>p.id===book.part);return selectPart(PARTS[i+(a==='next'?1:-1)].id);}
  if(a==='sketch-add'||a==='sketch-undo'){const owner=b.dataset.owner,container=b.closest('.sketch'),id=book.mode==='learn'?'Q1d':book.part,d=structuredClone((book.mode==='learn'?book.tutorials.T1?.drawing:answer(book,id,'drawing',owner))||{elements:[]});if(a==='sketch-undo')d.elements.pop();else{const kind=container.querySelector('[data-sketch-kind]').value;d.elements.push({kind,role:['load','effort','fulcrum'].includes(kind)?kind:undefined,x:Math.max(20,Math.min(580,Number(container.querySelector('[data-sketch-x]').value)||300)),y:Math.max(55,Math.min(220,Number(container.querySelector('[data-sketch-y]').value)||130)),label:container.querySelector('[data-sketch-label]').value.trim()||(['load','effort','fulcrum'].includes(kind)?kind:'')});}sketchSave(owner,d);}
 }
 nav.addEventListener('click',action);pane.addEventListener('click',action);modal.addEventListener('click',action);
 const api={
  allowChange(next){if(initializing||book.mode!=='challenge')return true;const part=PART_BY_ID[book.part];if(!app.get().held){tell('Hold Level before making this challenge change.');return false;}const allowed=part.allowed??[];if(Object.keys(next).some(k=>next[k]!==app.get().state[k]&&!allowed.includes(k))){tell('This step keeps that quantity fixed. Use the named variable or Free Play.');return false;}return true;},
  changed(before,next,held){if(initializing||sameState(before,next))return;interrupt();changes.push({at:stamp(),before:snapshot(before,held),after:snapshot(next,held),driver:book.team.driver});event(book,'control-change',{before,after:next,held});if(book.mode==='challenge')invalidateChecks(book,book.part==='Q14a'?[book.part,'Q14c']:[book.part]);storeWorkbench();refreshCheckStatus();persist();},
  resetting(){interrupt();storeWorkbench();persist();},
  supportViewed(source,resource){supportViewed(book,source,resource);persist();},
  recordAction(type){event(book,type);persist();},
  allowSwap(){if(book.mode!=='challenge')return true;const p=PART_BY_ID[book.part];if(!p.swap||!app.get().held||!predictionReady(book,p)){tell('Hold level and record both learners’ swap predictions in Q9b first.');return false;}event(book,'positions-swapped');persist();return true;},
  allowMath(){if(book.mode!=='challenge')return true;const part=PART_BY_ID[book.part];const own=part.fields.some(f=>f.prediction);if(own&&!predictionReady(book,{...part,prediction:true})||part.prediction&&!predictionReady(book,part)){tell('Record each prediction before showing the math.');return false;}event(book,'math-viewed');persist();return true;},
  beforeRelease(){flushDrafts();if(book.mode!=='challenge')return true;const part=PART_BY_ID[book.part];if(!part.trial){tell('Record this step, then continue to its release-and-observe step.');return false;}if(!predictionReady(book,part)){tell('Record each learner’s prediction before Release. It is not graded for correctness.');return false;}if(part.tableRow&&!book.trials.some(t=>t.part===part.id)){const predicted=Number(answer(book,part.id,'predictedMass',book.team.driver));if(!Number.isFinite(predicted)||predicted<25||predicted>1000||predicted%25!==0||app.get().state.effortMass!==predicted){tell('For the first trial, set effort mass to the driver’s prediction. Use a legal 25 g step; revisions retain the original prediction.');return false;}}if(part.design&&!book.workbenches.Q14a){tell('Create and record your Q14a design first.');return false;}return true;},
  held(){interrupt();storeWorkbench();persist();},
  released(){if(book.mode!=='challenge')return;const part=PART_BY_ID[book.part];const source=part.prediction===true?part.id:part.prediction;pending={id:crypto.randomUUID(),part:part.id,startedAt:stamp(),completedAt:null,driver:book.team.driver,setup:snapshot(app.get().state,true),predictions:structuredClone(source?book.answers[source]??{}:{}),changes:structuredClone(changes),result:null,settled:false,interrupted:false};changes=[];book.trials.push(pending);invalidateChecks(book,[part.id,...PARTS.filter(p=>p.requiresTrial===part.id).map(p=>p.id)]);refreshCheckStatus();book.coverage.Routine=true;storeWorkbench();persist();renderControls();}
 };
 let reminderShown=false;
 setInterval(()=>{if(pending&&(app.get().held||!sameState(app.get().state,pending.setup.state))){interrupt();storeWorkbench();persist();renderControls();}if(pending){const w=app.get(),motion=app.motion(),elapsed=Date.now()-Date.parse(pending.startedAt),settled=Math.abs(motion.velocity)<Math.PI/1800&&Math.abs(motion.angle-restingAngle(w.state))<Math.PI/1800;const out=$('#trial-state');if(out)out.textContent='Observing… wait for settled motion.';if(elapsed>500&&settled){pending.result=measures(pending.setup.state).direction;pending.settled=true;pending.completedAt=stamp();pending.motion={...motion};pending.engineStatus=balanceStatus(w.state,motion,false);event(book,'trial-completed',{trialId:pending.id});const result=pending.result;pending=null;persist();if(out)out.textContent=`Recorded: ${{balance:'Level',load:'Load Side Down',effort:'Effort Side Down'}[result]}. Now enter your observation.`;}}
  const mins=book.team.reminderMinutes;if(book.team.mode==='pair'&&mins&&book.team.rotationStarted){const due=Date.now()-Date.parse(book.team.rotationStarted)>mins*60000;if(due&&!reminderShown){tell('Role reminder: wait for your teacher’s call, then use Swap Roles.');reminderShown=true;}if(!due)reminderShown=false;}
 },150);
 addEventListener('pagehide',()=>{storeWorkbench();persist();});
 pane.addEventListener('focusout',()=>{flushDrafts();persist();});
 pane.addEventListener('toggle',e=>{if(e.target.open&&e.target.closest('.vocabulary'))api.supportViewed('reference',e.target.querySelector('summary').textContent);},true);
 resumeNotebook();
 return api;
}
