import { PARTS,PART_BY_ID,QUESTIONS,LESSONS } from './curriculum.js';
import { DEFAULT,valid,arm,setMass,setDistance,move,measures,restingAngle,balanceStatus } from './model.js';
import { NOTEBOOK_KEY,MAX_BACKUP_BYTES,loadNotebook,saveNotebook,parseBackup,answer,response,learners,stamp,event,rotate,visitLesson,predictionReady,snapshot,latestTrial,checkPart,coverage,invalidateChecks,sameState,supportViewed,revalidateChecks } from './notebook.js';
import {escapeHTML as esc,drawingSVG,reportHTML} from './report.js';
import {emphasizeTerms,vocabularyReference} from './reference.js';
import {studentText,identifyOrder,identifyRoles,isIdentify,identifyStreak,indexHTML,lessonIndexHTML,feedbackHTML,sharedSession,updateIntro,displayNumber} from './student-ui.js';
import {TEACHING,sourcePart,targetPart,latestPrediction,freshPrediction,recordPrediction,stalePredictions,setupMismatch} from './guided.js';
import {REPRESENTATION} from './representation.js';
const $=s=>document.querySelector(s);
const button=(action,label,extra='')=>`<button data-lab="${action}" ${extra}>${label}</button>`;
const options=(values,value)=>values.map(v=>`<option value="${esc(typeof v==='object'?v.value:v)}" ${String(typeof v==='object'?v.value:v)===String(value)?'selected':''}>${esc(typeof v==='object'?v.label:v)}</option>`).join('');
export function mountLearning(app){
 let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error('Browser storage is unavailable.');},setItem(){throw Error();}};}
 const loaded=loadNotebook(storage,$('#build-identity').textContent);let book=loaded.book,manifest=null,pending=null,changes=[],initializing=false,saveError=loaded.error,recoveryRaw=loaded.recovery;
 if(loaded.fresh)book.freeWorkbench=snapshot(app.get().state,app.get().held);
 sharedSession(book);if(book.mode==='learn'&&book.returnTo)book.part=book.returnTo;book.mode='challenge';book.returnTo=null;let indexOpen=false,referenceOpen=false,pickFeedback=null;
 const drafts=new Map();
 fetch('./build-manifest.json').then(r=>r.json()).then(x=>manifest=x).catch(()=>{});
 for(const t of book.trials)if(!t.completedAt){t.interrupted=true;t.completedAt=stamp();}
 const nav=document.createElement('nav');nav.id='lab-navigation';nav.setAttribute('aria-label','Assignment Progress');nav.innerHTML='<strong>Guided Assignment</strong><output id="save-status" role="status"></output>';$('#top').append(nav);
 const pane=document.createElement('aside');pane.id='notebook';pane.setAttribute('aria-label','Learning Notebook');document.querySelector('#app').append(pane);
 const reopen=document.createElement('button');reopen.id='notebook-reopen';reopen.textContent='Show Notebook';reopen.hidden=true;reopen.onclick=()=>{pane.hidden=false;reopen.hidden=true;};$('#app').append(reopen);
 const modal=document.createElement('dialog');modal.id='session-dialog';modal.innerHTML='<h2>Recover Saved Work</h2><div id="session-body"></div>';$('#app').append(modal);
 function persist(){if(recoveryRaw){$('#save-status').textContent='Unreadable Save Kept';return;}const saved=saveNotebook(storage,book);saveError=saved.ok?saveError:saved.error;$('#save-status').textContent=saveError?'Backup Needed':'Saved On This Device';$('#save-status').title=saveError??'Progress stays in this browser. Download a backup before changing devices.';}
 function tell(message){app.notice(message);const out=$('#lab-feedback');if(out)out.textContent=message;}
 function status(){app.pauseCue?.(app.get().held?'Paused For Setup And Prediction':'Observing The Released Lever');}
 function flushDrafts(){for(const d of drafts.values()){const current=answer(book,d.id,d.key,d.owner);if(JSON.stringify(current)!==JSON.stringify(d.previous))book.history.push({id:d.id,key:d.key,owner:d.owner,value:structuredClone(current),previous:d.previous,at:stamp(),driver:d.driver,representation:REPRESENTATION});}drafts.clear();}
 function storeWorkbench(){flushDrafts();if(initializing)return;const w=snapshot(app.get().state,app.get().held);if(book.mode==='challenge')book.workbenches[book.part]=w;else if(book.mode==='free')book.freeWorkbench=w;}
 function loadWorkbench(w){initializing=true;app.load(w);initializing=false;}
 function interrupt(){if(pending){pending.interrupted=true;pending.settled=false;pending.result=null;pending.completedAt=stamp();event(book,'trial-interrupted',{trialId:pending.id});pending=null;app.hold();}}
 function selectPart(id,preserveCurrent=true,carry=false){indexOpen=false;referenceOpen=false;if(isIdentify(id))id=identifyOrder[Math.min(identifyStreak(book),2)];interrupt();if(preserveCurrent)storeWorkbench();book.mode='challenge';book.part=id;changes=[];
  const w=!carry&&book.workbenches[id]?book.workbenches[id]:snapshot(app.get().state,true);loadWorkbench({...w,held:true});book.workbenches[id]=snapshot(app.get().state,true);app.math(false);
  if(book.guided.startedAt){const part=PART_BY_ID[id];book.guided.teaching[id]={lesson:part.lesson,at:stamp(),contentRevision:book.assignment.questions[id]};supportViewed(book,'embedded',part.lesson,id);}
  render();pane.scrollTop=0;persist();
 }
 function resumeNotebook(){sharedSession(book);book.mode='challenge';revalidateChecks(book);selectPart(book.part,false);}
 function refreshCheckStatus(){if(book.mode!=='challenge'||indexOpen)return;const out=$('#lab-feedback');if(out)out.innerHTML=feedbackHTML(book.checks[book.part]);}
 function autoCheck(){if(!book.guided.startedAt||indexOpen||referenceOpen||isIdentify(book.part))return;storeWorkbench();checkPart(book,PART_BY_ID[book.part],app.get());updateIntro(book);refreshCheckStatus();persist();}
 function identifyPart(role){if(!book.guided.startedAt||indexOpen||referenceOpen||!isIdentify(book.part)||identifyStreak(book)>=3)return false;
  const streak=identifyStreak(book),id=identifyOrder[streak],expected=identifyRoles[streak],correct=role===expected;
  response(book,id,'role',role[0].toUpperCase()+role.slice(1));event(book,'identify-picked',{part:id,expected,picked:role,correct,streak:correct?streak+1:0});
  if(correct)checkPart(book,PART_BY_ID[id],app.get());else invalidateChecks(book,identifyOrder,'Complete all three part choices in a row.');
  pickFeedback={role,correct};if(streak+1<3||!correct)book.part=identifyOrder[correct?streak+1:0];storeWorkbench();render();persist();return true;
 }
 function simulator(part){const w=app.get(),state=w.state;return `<div class="mini-controls"><p class="state-note">${w.held?'Paused For Setup And Prediction':'Observing The Released Lever'}</p><div class="lab-controls">${[['loadMass','Load Mass (g)',state.loadMass],['effortMass','Effort Push (g-equivalent)',state.effortMass],['load','Load Arm (mm)',arm(state,'load')],['effort','Effort Arm (mm)',arm(state,'effort')],['fulcrum','Fulcrum Position (mm)',state.fulcrum]].map(([key,label,value])=>`<label>${label}<input data-control="${key}" aria-label="Notebook ${label}" type="number" step="25" value="${value}"></label>`).join('')}</div><p class="lab-note">The hand's size stays constant. ${state.effortMass} g-equivalent is a push of ${(state.effortMass/1000*9.81).toFixed(3)} N. You do not need to convert it yourself.</p><div class="button-row">${part?.trial?button('test',w.held?(part.prediction?'Record Prediction And Watch':'Test This Setup'):'Pause And Adjust'):''}${part?.id==='Q10a'?button('side','Side View'):''}${part?.swap?button('swap','Swap Positions'):''}</div><output id="trial-state" aria-live="polite"></output></div>`;}
 function fieldHTML(part,f,owner){const v=answer(book,part.id,f.key,owner);let control;const attrs=`data-answer="${esc(f.key)}" data-owner="${owner}" data-response-part="${part.id}"`;
  if(f.type==='sketch')return sketchHTML(part.id,owner,v);
  let choices=f.options;
  if(f.key==='trialId')choices=book.trials.filter(t=>/^Q7b/.test(t.part)&&t.result==='balance'&&t.settled&&!t.interrupted).map(t=>({value:t.id,label:`Effort Arm ${t.setup.effortArm} mm · ${t.setup.state.effortMass} g · ${t.startedAt.slice(11,19)}`}));
  if(f.type==='select')return `<div class="response-field"><strong>${esc(studentText(f.label))}</strong><div class="answer-choices" role="group" aria-label="${esc(studentText(f.label))}">${choices.map(choice=>{const value=typeof choice==='object'?choice.value:choice,label=typeof choice==='object'?choice.label:choice;return button('choose',esc(studentText(label)),`data-answer="${f.key}" data-owner="${owner}" data-response-part="${part.id}" data-value="${esc(value)}" aria-pressed="${String(v)===String(value)}"`);}).join('')}</div></div>`;
  else if(f.type==='text')control=`<textarea ${attrs} rows="3" maxlength="10000">${esc(v)}</textarea>`;
  else control=`<input ${attrs} type="number" value="${esc(v)}" step="any">`;
  return `<label class="response-field">${esc(studentText(f.label))}${f.prediction?'<small>Saved before testing; prediction correctness is not graded.</small>':''}${control}</label>`;
 }
 function sketchHTML(id,owner,value){return `<div class="sketch" data-sketch-owner="${owner}"><b>Your Lever Sketch</b><div class="drawing-surface" tabindex="0" aria-label="Draw Your Lever Sketch">${drawingSVG(value||{elements:[]})}</div><p class="lab-note">Draw with a pointer, or build the entire diagram with the keyboard controls below. Add all three role labels. Undo removes your last addition.</p><div class="sketch-controls"><label>Component<select data-sketch-kind>${options(['beam','load','fulcrum','effort','label'],'beam')}</select></label><label>Horizontal Position<input data-sketch-x type="number" min="20" max="580" value="300"></label><label>Vertical Position<input data-sketch-y type="number" min="55" max="220" value="130"></label><label>Label<input data-sketch-label maxlength="100" placeholder="Role, mass, arm, or note"></label></div>${button('sketch-add','Add Component',`data-owner="${owner}"`)}${button('sketch-undo','Undo',`data-owner="${owner}"`)}</div>`;}
 function render(){status();const started=!!book.guided.startedAt;app.identify?.(started&&!indexOpen&&!referenceOpen&&isIdentify(book.part),pickFeedback);pane.hidden=false;reopen.hidden=true;
  const heading=`<div class="notebook-heading">${button('hide','Hide Notebook')}${button('index','Question Index')}${button('reference','Vocabulary')}</div>`;
  if(referenceOpen){pane.innerHTML=heading+`<h2>Vocabulary And Reference</h2>${button('back','Back To Question')}${vocabularyReference}`;return;}
  if(indexOpen){pane.innerHTML=heading+indexHTML(book);return;}
  if(!started){pane.innerHTML=heading+`<h2>Learn By Doing</h2><p>${emphasizeTerms(TEACHING.T12[1])}</p><h3>A Weight And A Push</h3><p>${emphasizeTerms('The hanging load has weight from gravity. The hand supplies effort by pushing down. Its size and mass do not set the push.')}</p><div class="teaching-card"><b>Worked Example</b><p>${emphasizeTerms(TEACHING.T0[2])}</p><small>We show the matching Newton value automatically. No conversion is required.</small></div><p><b>What Does 100 g-Equivalent Describe?</b></p><div class="answer-choices">${button('calibration','A Push Equal To A 100 g Object’s Weight','data-value="push"')}${button('calibration','The Mass Of The Hand','data-value="hand"')}</div><p id="calibration-feedback" role="status">${book.guided.calibrationChoice==='push'?'Exactly: it is a force calibration, not hand mass.':book.guided.calibrationChoice?'The hand supplies a push. The number compares its force with an object’s weight; try that choice.':''}</p>${button('begin','Begin The Assignment',book.guided.calibrationChoice!=='push'?'disabled':'')}<p class="lab-note">Your controls stay usable while the beam pauses. Save recovery copies before changing browser profiles, devices, or preview addresses.</p>`;return;}
  const part=PART_BY_ID[book.part],lesson=TEACHING[part.lesson],identifying=isIdentify(part.id),streak=identifyStreak(book),source=sourcePart(part),predictionFields=part.trial&&source&&source.id!==part.id&&!freshPrediction(book,part,app.get().state)?source.fields.filter(f=>f.prediction):[];
  const identification=identifying?`<h3>${streak<3?'Select The '+identifyRoles[streak][0].toUpperCase()+identifyRoles[streak].slice(1):'All Three Parts Identified'}</h3><p>Select a part in the workbench, or use these keyboard-accessible buttons.</p><div class="identify-choices">${[['load','Hanging Weight','&#9679;'],['effort','Pressing Hand','&#9759;'],['fulcrum','Support','&#9650;']].map(([role,label,icon])=>button('identify',`<span aria-hidden="true">${icon}</span>${label}`,`data-pick="${role}" class="identify-candidate ${pickFeedback?.role===role?(pickFeedback.correct?'right':'wrong'):''}" ${streak===3?'disabled':''}`)).join('')}</div><p id="identify-feedback" role="status">${pickFeedback?(pickFeedback.correct?'Correct. ':'That is a different role. Start again with Effort. '):''}${streak} Of 3 Correct In A Row</p>`:'';
  const setup=part.target??part.initial;
  const requested=setup?`<p class="setup-target"><b>${part.setup?'Set Up':'Start With'}:</b> load ${setup.loadMass} g; effort push ${setup.effortMass} g-equivalent; load arm ${arm(setup,'load')} mm; effort arm ${arm(setup,'effort')} mm; fulcrum ${setup.fulcrum} mm. ${part.allowed?.length?'Adjust the named quantity for this investigation.':''}</p>`:'';
  const evidence=(part.references??[]).map(id=>{const t=latestTrial(book,id);return t?`<details><summary>Your Earlier Trial</summary><p>Load ${t.setup.state.loadMass} g at ${t.setup.loadArm} mm; effort ${t.setup.state.effortMass} ${t.representation===REPRESENTATION?'g-equivalent':'g in the earlier apparatus'} at ${t.setup.effortArm} mm.</p></details>`:'';}).join('');
  const nextLabel=!part.trial&&part.fields.some(f=>f.prediction)?(PARTS[PARTS.indexOf(part)+1]?.trial?'Record Prediction And Watch':'Record Prediction And Continue'):'Continue';
  pane.innerHTML=heading+`<small class="packet-location">${esc(part.page)} / Packet Question ${part.question}</small><h2>Question ${displayNumber(part.id)}: ${esc(identifying?'Identify The Parts':part.title)}</h2><div class="teaching-card"><h3>${esc(lesson[0])}</h3><p>${emphasizeTerms(lesson[1])}</p><p class="worked-example"><b>Worked Example:</b> ${emphasizeTerms(lesson[2])}</p></div>${identifying?identification:`${part.instructions?`<p>${emphasizeTerms(studentText(part.instructions))}</p>`:''}${requested}${part.id==='Q10a'?button('side','Side View / Diagram'):''}${part.priorTrial?button('q7','Use Or Recreate An Earlier Trial'):''}${evidence}${predictionFields.length?`<div class="prediction-update"><b>Prediction For This Setup</b><p>The setup changed or needs a recorded prediction. Earlier predictions stay saved.</p>${predictionFields.map(f=>fieldHTML(source,f,'A')).join('')}</div>`:''}${part.fields.map(f=>fieldHTML(part,f,f.personal?'A':'shared')).join('')}${part.setup||part.trial||part.initial||part.fields.some(f=>f.prediction)?simulator(part):''}`}<div class="button-row">${button('next',nextLabel,identifying&&streak<3?'disabled':'')}</div>${identifying?'':`<div id="lab-feedback" role="status">${feedbackHTML(book.checks[part.id])}</div>`}`;
  wireFields();wireSketches();
 }
 function wireFields(){pane.querySelectorAll('input[data-answer],textarea[data-answer]').forEach(input=>input.addEventListener('input',()=>{const responsePart=input.dataset.responsePart??book.part;const key=responsePart+'|'+input.dataset.owner+'|'+input.dataset.answer;if(!drafts.has(key))drafts.set(key,{id:responsePart,key:input.dataset.answer,owner:input.dataset.owner,previous:structuredClone(answer(book,responsePart,input.dataset.answer,input.dataset.owner)),driver:book.team.driver});response(book,responsePart,input.dataset.answer,input.value,input.dataset.owner,false);if(PART_BY_ID[responsePart].fields.find(f=>f.key===input.dataset.answer)?.prediction)for(const prediction of book.guided.predictions)if(prediction.source===responsePart&&!prediction.invalidatedAt)prediction.invalidatedAt=stamp();refreshCheckStatus();persist();}));
  pane.querySelectorAll('input[data-answer],textarea[data-answer]').forEach(input=>input.addEventListener('change',autoCheck));
  pane.querySelectorAll('[data-control]').forEach(input=>input.addEventListener('change',()=>{const s=app.get().state,k=input.dataset.control;app.change(k.endsWith('Mass')?setMass(s,k==='loadMass'?'load':'effort',input.value):k==='fulcrum'?move(s,k,input.value):setDistance(s,k,input.value));render();autoCheck();}));

 }
 function renderControls(){const controls=pane.querySelector('.mini-controls');if(controls){controls.outerHTML=simulator(PART_BY_ID[book.part]);pane.querySelectorAll('[data-control]').forEach(input=>input.addEventListener('change',()=>{const s=app.get().state,k=input.dataset.control;app.change(k.endsWith('Mass')?setMass(s,k==='loadMass'?'load':'effort',input.value):k==='fulcrum'?move(s,k,input.value):setDistance(s,k,input.value));render();autoCheck();}));}}
 function sketchSave(owner,drawing){drawing.representation=REPRESENTATION;if(book.mode==='learn'){book.tutorials.T1??={};book.tutorials.T1.drawing=drawing;}else response(book,book.part,'drawing',drawing,owner);autoCheck();persist();const surface=pane.querySelector(`[data-sketch-owner="${owner}"] .drawing-surface`);if(surface)surface.innerHTML=drawingSVG(drawing);}
 function wireSketches(){for(const container of pane.querySelectorAll('.sketch')){const surface=container.querySelector('.drawing-surface'),owner=container.dataset.sketchOwner;let points=null;
   const point=e=>{const r=surface.getBoundingClientRect();return [Math.max(0,Math.min(600,(e.clientX-r.left)*600/r.width)),Math.max(0,Math.min(280,(e.clientY-r.top)*280/r.height))];};
   surface.addEventListener('pointerdown',e=>{points=[point(e)];surface.setPointerCapture(e.pointerId);});surface.addEventListener('pointermove',e=>{if(points&&points.length<5000)points.push(point(e));});surface.addEventListener('pointerup',()=>{if(!points)return;const id=book.mode==='learn'?'Q1d':book.part;const d=structuredClone((book.mode==='learn'?book.tutorials.T1?.drawing:answer(book,id,'drawing',owner))||{elements:[],representation:REPRESENTATION});d.elements.push({kind:'stroke',x:0,y:0,points,label:''});points=null;sketchSave(owner,d);});
  }}
 function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function session(){storeWorkbench();persist();$('#session-body').innerHTML=`<p>Your anonymous classwork saves in this browser. A recovery copy lets you resume on another device.</p>${saveError?`<p>${esc(saveError)}</p>`:''}${recoveryRaw?button('recovery','Download Unreadable Save'):''}${button('backup','Download Recovery Copy')}<label>Restore Saved Work<input id="restore-backup" type="file" accept=".json,application/json"></label><p id="restore-preview"></p>${button('restore','Replace With Reviewed Backup','disabled')}<p>Check the file before replacing this notebook. Your current work stays unchanged if validation fails.</p>${button('close-session','Done')}`;
  let candidate=null;$('#restore-backup').addEventListener('change',async e=>{candidate=null;modal.querySelector('[data-lab="restore"]').disabled=true;try{const file=e.target.files[0];if(!file||file.size>MAX_BACKUP_BYTES)throw Error('Choose a Lever Lab JSON backup smaller than 12 MB.');candidate=parseBackup(await file.text(),{build:$('#build-identity').textContent});$('#restore-preview').textContent=`Ready to restore ${candidate.history.length} revisions · saved ${candidate.updatedAt}`;modal.querySelector('[data-lab="restore"]').disabled=false;}catch(e){$('#restore-preview').textContent=e.message;}});
  modal.querySelector('[data-lab="restore"]').onclick=()=>{if(!candidate)return;
   const prepared=structuredClone(candidate);for(const t of prepared.trials)if(!t.completedAt){t.interrupted=true;t.completedAt=stamp();}
   const saved=saveNotebook(storage,prepared);if(!saved.ok){$('#restore-preview').textContent=saved.error+' Restore was not applied.';return;}
   interrupt();flushDrafts();book=prepared;sharedSession(book);changes=[];indexOpen=false;recoveryRaw=null;candidate=null;saveError=null;modal.close();resumeNotebook();};modal.showModal();
 }
 function commitPredictionFor(part){flushDrafts();const source=sourcePart(part);if(!source)return true;if(!predictionReady(book,{prediction:source.id})){tell('Record your prediction before the test. It may differ from the outcome.');return false;}recordPrediction(book,part,app.get().state);book.workbenches[source.id]=snapshot(app.get().state,true);checkPart(book,source,app.get());persist();return true;}
 function startTest(){const part=PART_BY_ID[book.part];if(!app.get().held){app.toggleHold();render();return;}if(part.prediction&&!commitPredictionFor(part))return;app.toggleHold();render();}
 function action(e){const b=e.target.closest('[data-lab]');if(!b)return;const a=b.dataset.lab;
  if(a==='calibration'){book.guided.calibrationChoice=b.dataset.value;event(book,'calibration-response',{value:b.dataset.value});render();persist();return;}
  if(a==='begin'){if(book.guided.calibrationChoice!=='push')return;book.guided.startedAt=stamp();supportViewed(book,'embedded','T0 / T12',book.part);return selectPart(book.part);}
  if(a==='reference'){referenceOpen=true;indexOpen=false;supportViewed(book,'reference','Vocabulary Index');render();persist();return;}
  if(a==='back'){referenceOpen=false;indexOpen=false;render();return;}
  if(a==='test')return startTest();
  if(a==='index'){interrupt();storeWorkbench();indexOpen=true;render();persist();return;}
  if(a==='question')return selectPart(b.dataset.part);
  if(a==='identify')return identifyPart(b.dataset.pick);
  if(a==='choose'){const id=b.dataset.responsePart??book.part;response(book,id,b.dataset.answer,b.dataset.value,b.dataset.owner);if(PART_BY_ID[id].fields.find(f=>f.key===b.dataset.answer)?.prediction)for(const p of book.guided.predictions)if(p.source===id&&!p.invalidatedAt)p.invalidatedAt=stamp();autoCheck();render();return;}
  if(a==='hide'){pane.hidden=true;reopen.hidden=false;return;}
  if(a==='session')return session();if(a==='close-session'){modal.close();return;}
  if(a==='recovery'){download('LeverLab-Unreadable-Save.json',recoveryRaw,'application/json');return;}
  if(a==='backup'){storeWorkbench();persist();download('LeverLab-Backup-'+book.id.slice(0,8)+'.json',JSON.stringify(book,null,2),'application/json');return;}
  if(a==='report'){if(!coverage(book).every(r=>r.complete)){tell('Complete the required question evidence before downloading the final work.');return;}storeWorkbench();persist();download('LeverLab-Student-Work-'+book.id.slice(0,8)+'.html',reportHTML(book,manifest),'text/html');return;}
  if(a==='hold'){app.toggleHold();renderControls();return;}if(a==='side'){app.side();return;}if(a==='swap'){app.swap();renderControls();return;}
  if(a==='q7')return selectPart('Q7b1');
  if(a==='check'){storeWorkbench();checkPart(book,PART_BY_ID[book.part],app.get());persist();render();return;}
  if(a==='next'){if(isIdentify(book.part)){if(identifyStreak(book)<3)return;return selectPart('Q1d',true,true);}autoCheck();if(!book.checks[book.part]?.complete)return;const part=PART_BY_ID[book.part];if(!part.trial&&part.fields.some(f=>f.prediction)&&!commitPredictionFor(part))return;const i=PARTS.findIndex(p=>p.id===book.part);if(i===PARTS.length-1){indexOpen=true;render();return;}selectPart(PARTS[i+1].id,true,true);const next=PART_BY_ID[book.part];if(next.trial&&next.prediction&&freshPrediction(book,next,app.get().state)&&!setupMismatch(next,app.get().state).length){app.toggleHold();render();}return;}
  if(a==='sketch-add'||a==='sketch-undo'){const owner=b.dataset.owner,container=b.closest('.sketch'),id=book.mode==='learn'?'Q1d':book.part,d=structuredClone((book.mode==='learn'?book.tutorials.T1?.drawing:answer(book,id,'drawing',owner))||{elements:[],representation:REPRESENTATION});if(a==='sketch-undo')d.elements.pop();else{const kind=container.querySelector('[data-sketch-kind]').value;d.elements.push({kind,role:['load','effort','fulcrum'].includes(kind)?kind:undefined,x:Math.max(20,Math.min(580,Number(container.querySelector('[data-sketch-x]').value)||300)),y:Math.max(55,Math.min(220,Number(container.querySelector('[data-sketch-y]').value)||130)),label:container.querySelector('[data-sketch-label]').value.trim()||(['load','effort','fulcrum'].includes(kind)?kind:'')});}sketchSave(owner,d);}
 }
 nav.addEventListener('click',action);pane.addEventListener('click',action);modal.addEventListener('click',action);
 const api={
  identifyPart,
  isIdentifying:()=>!!book.guided.startedAt&&!indexOpen&&!referenceOpen&&isIdentify(book.part)&&identifyStreak(book)<3,
  allowChange(next){if(initializing)return true;if(!app.get().held){interrupt();app.hold();}return true;},
  changed(before,next,held){if(initializing||sameState(before,next))return;interrupt();changes.push({at:stamp(),before:snapshot(before,held),after:snapshot(next,held),driver:book.team.driver});event(book,'control-change',{before,after:next,held});if(book.mode==='challenge')invalidateChecks(book,book.part==='Q14a'?[book.part,'Q14c']:[book.part]);stalePredictions(book,PART_BY_ID[book.part],next);storeWorkbench();refreshCheckStatus();persist();status();},
  resetting(){interrupt();storeWorkbench();persist();},
  supportViewed(source,resource){supportViewed(book,source,resource);persist();},
  recordAction(type){event(book,type);persist();},
  allowSwap(){interrupt();app.hold();event(book,'positions-swapped');persist();return true;},
  allowMath(){supportViewed(book,'help','Math And Turning Effects');event(book,'math-viewed');persist();return true;},
  beforeRelease(){flushDrafts();if(!book.guided.startedAt){tell('The beam is paused while you read the introduction. The controls stay usable.');return false;}const part=PART_BY_ID[book.part];if(!part.trial){tell('Record this step, then continue to its release-and-observe step.');return false;}if(!predictionReady(book,part)||!freshPrediction(book,part,app.get().state)){tell('Record your prediction before Release. It is not graded for correctness.');return false;}if(setupMismatch(part,app.get().state).length){tell('Set the fixed values shown for this investigation before starting the test. All controls remain usable.');return false;}if(part.tableRow&&!book.trials.some(t=>t.part===part.id)){const predicted=Number(answer(book,part.id,'predictedMass',book.team.driver));if(!Number.isFinite(predicted)||predicted<25||predicted>1000||predicted%25!==0||app.get().state.effortMass!==predicted){tell('For the first trial, set effort push to your prediction. Use a legal 25 g-equivalent step; revisions retain the original prediction.');return false;}}if(part.design&&!book.workbenches.Q14a){tell('Create and record your design first.');return false;}return true;},
  held(){interrupt();storeWorkbench();persist();status();},
  released(){if(book.mode!=='challenge')return;const part=PART_BY_ID[book.part];const source=part.prediction===true?part.id:part.prediction;pending={id:crypto.randomUUID(),part:part.id,representation:REPRESENTATION,predictionId:part.prediction?latestPrediction(book,part.id)?.id:null,startedAt:stamp(),completedAt:null,driver:book.team.driver,setup:snapshot(app.get().state,true),predictions:structuredClone(source?book.answers[source]??{}:{}),changes:structuredClone(changes),result:null,settled:false,interrupted:false};changes=[];book.trials.push(pending);invalidateChecks(book,[part.id,...PARTS.filter(p=>p.requiresTrial===part.id).map(p=>p.id)]);refreshCheckStatus();book.coverage.Routine=true;storeWorkbench();persist();renderControls();}
 };

 setInterval(()=>{if(pending&&(app.get().held||!sameState(app.get().state,pending.setup.state))){interrupt();storeWorkbench();persist();renderControls();}if(pending){const w=app.get(),motion=app.motion(),elapsed=Date.now()-Date.parse(pending.startedAt),settled=Math.abs(motion.velocity)<Math.PI/1800&&Math.abs(motion.angle-restingAngle(w.state))<Math.PI/1800;const out=$('#trial-state');if(out)out.textContent='Observing… wait for settled motion.';if(elapsed>500&&settled){pending.result=measures(pending.setup.state).direction;pending.settled=true;pending.completedAt=stamp();pending.motion={...motion};pending.engineStatus=balanceStatus(w.state,motion,false);event(book,'trial-completed',{trialId:pending.id});const result=pending.result;pending=null;autoCheck();persist();if(out)out.textContent=`Recorded: ${{balance:'Level',load:'Load Side Down',effort:'Effort Side Down'}[result]}. Now enter your observation.`;}}
 },150);
 addEventListener('pagehide',()=>{storeWorkbench();persist();});
 pane.addEventListener('focusout',()=>{flushDrafts();persist();});
 addEventListener('pointerup',e=>{if(!e.target.closest?.('button,input,textarea,select')&&book.mode==='challenge'&&!indexOpen)autoCheck();});
 addEventListener('keyup',e=>{if(e.key?.startsWith('Arrow'))autoCheck();});
 pane.addEventListener('toggle',e=>{if(e.target.open&&e.target.closest('.vocabulary'))api.supportViewed('reference',e.target.querySelector('summary').textContent);},true);
 resumeNotebook();
 return api;
}
